import { DeleteOutlined, DownOutlined, EditOutlined, PlusOutlined, RobotOutlined, StopOutlined } from "@ant-design/icons";
import { Alert, Button, Checkbox, Dropdown, Empty, Form, Input, List, Modal, Popconfirm, Segmented, Select, Space, Spin, Tag, Tooltip, Typography, message } from "antd";
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { getLocalizedErrorMessage } from "@/components/request";
import type { PdfTextSelection } from "@/components/ui";
import { cancelPreanalysisTask, createPreanalysisTask, deleteLearningPreset, getLatestPreanalysisTask, getPreanalysisTask, listLearningPresets, listPreanalysisDrafts, publishPreanalysisDrafts, putLearningPreset, runPreanalysisTask, updateLearningPreset, type LearningCapability, type LearningPreset, type PreanalysisTask } from "./api";
import { capabilitiesForFamilies, capabilityFamilies, capabilityFamily, capabilityFamilyI18nKey, chooseFamilyCapability, type CapabilityFamily } from "./capabilityFamilies";
import "./DocumentLearningPanel.scss";

export interface DocumentAnalysisSelection { selections:PdfTextSelection[];requestId:number }
interface Props { datasetId:string;documentId:string;revision?:string;capabilities:LearningCapability[];localAvailable:boolean;analysisSelection?:DocumentAnalysisSelection;onRequestParagraphSelection?:()=>void }
type Drafts={presets:LearningPreset[];contents:Record<string,unknown>[]};

const parseValue=(raw:string)=>{try{return JSON.parse(raw||"{}") as Record<string,unknown>}catch{return {}}};
const displayText=(value:unknown):string=>{if(typeof value==="string"||typeof value==="number")return String(value).trim();if(value&&typeof value==="object"){const row=value as Record<string,unknown>;const sentence=displayText(row.sentence??row.text??row.example);const translation=displayText(row.translation);return [sentence,translation].filter(Boolean).join(" — ")}return ""};
export const presetDisplayValue=(raw:string)=>{const value=parseValue(raw);const semanticKeys=["meaning_in_context","meaning","translation","definition"];const semantic=semanticKeys.map(key=>displayText(value[key])).find(Boolean)||Object.entries(value).filter(([key])=>!["examples","example","phonetic","pinyin","citations","dictionary_meaning"].includes(key)).map(([,item])=>displayText(item)).find(Boolean)||"";const definition=displayText(value.definition);const dictionaryMeaning=displayText(value.dictionary_meaning)||(definition&&definition!==semantic?definition:"");const rawExamples=value.examples??value.example;const examples=(Array.isArray(rawExamples)?rawExamples:[rawExamples]).map(displayText).filter(Boolean);return {semantic,dictionaryMeaning,examples}};
export const displayPresetKey=(key:string)=>{const parts=key.split("\x1f");return parts[0]==="learning-v1"&&parts.length>=5?parts[4]:key};
export const capabilitySupportsAnalysisText=(capability:LearningCapability,text:string)=>{const chars=Array.from(text.trim());if(!chars.length)return true;const hasHan=chars.some(char=>/\p{Script=Han}/u.test(char));const hasLatin=chars.some(char=>/\p{Script=Latin}/u.test(char));return capability.languages.includes("*")||(hasHan&&capability.languages.some(language=>["zh-Hans","zh-Hant","lzh"].includes(language)))||(hasLatin&&capability.languages.includes("en"))};

export default function DocumentLearningPanel({datasetId,documentId,revision,capabilities,localAvailable,analysisSelection,onRequestParagraphSelection}:Props){
 const initialSelections=analysisSelection?.selections||[];
 const {t}=useTranslation(); const [presets,setPresets]=useState<LearningPreset[]>([]); const [filter,setFilter]=useState("all"); const [selectedPresets,setSelectedPresets]=useState<string[]>([]); const [editor,setEditor]=useState<{preset?:LearningPreset;open:boolean}>({open:false}); const [analysisOpen,setAnalysisOpen]=useState(Boolean(analysisSelection)); const [selected,setSelected]=useState<string[]>(capabilities.map(x=>x.key)); const [analysisScope,setAnalysisScope]=useState<"document"|"selection">(analysisSelection?"selection":"document"); const [analysisItems,setAnalysisItems]=useState<PdfTextSelection[]>(initialSelections); const [analysisText,setAnalysisText]=useState(initialSelections.map(item=>item.text).join("\n\n")); const [analysisDirection,setAnalysisDirection]=useState(""); const [task,setTask]=useState<PreanalysisTask>(); const [drafts,setDrafts]=useState<Drafts>(); const [selectedDrafts,setSelectedDrafts]=useState<string[]>([]); const [starting,setStarting]=useState(false); const [stopping,setStopping]=useState(false); const [publishing,setPublishing]=useState(false); const [loading,setLoading]=useState(false); const [deleting,setDeleting]=useState(false); const [form]=Form.useForm();
 const capabilityMap=useMemo(()=>new Map(capabilities.map(item=>[item.key,item])),[capabilities]);
 const selectionCapabilities=useMemo(()=>capabilities.filter(item=>capabilitySupportsAnalysisText(item,analysisText)),[analysisText,capabilities]);
 const families=useMemo(()=>capabilityFamilies(capabilities),[capabilities]);
 const capabilityLabel=(key:string)=>t(capabilityFamilyI18nKey(capabilityFamily(key)));
 const presetValue=(item:LearningPreset)=>{const display=presetDisplayValue(item.value_json);const detail=<div className="document-analysis__value-tooltip"><div><strong>{t("learning.contextMeaning")}</strong><div>{display.semantic||"—"}</div></div>{display.dictionaryMeaning?<div className="document-analysis__value-examples"><strong>{t("learning.dictionaryMeaning")}</strong><div>{display.dictionaryMeaning}</div></div>:null}{display.examples.length?<div className="document-analysis__value-examples"><strong>{t("learning.field.examples")}</strong><ul>{display.examples.map((example,index)=><li key={`${index}-${example}`}>{example}</li>)}</ul></div>:null}</div>;return <Tooltip title={detail} placement="left"><Typography.Paragraph className="document-analysis__value" ellipsis={{rows:2}}>{display.semantic||"—"}</Typography.Paragraph></Tooltip>};
 const load=async()=>{if(!localAvailable)return;setLoading(true);try{setPresets(await listLearningPresets("document",documentId))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[documentId,localAvailable]);
 useEffect(()=>{let active=true;if(!localAvailable)return()=>{active=false};getLatestPreanalysisTask(datasetId,documentId).then(latest=>{if(active)setTask(latest)}).catch(()=>{});return()=>{active=false}},[datasetId,documentId,localAvailable]);
 const taskActive=starting||task?.status==="queued"||task?.status==="running";
 useEffect(()=>{if(!task||!["queued","running"].includes(task.status))return;let active=true;const poll=async()=>{try{const next=await getPreanalysisTask(task.id);if(active)setTask(next)}catch{/* Keep the last authoritative state and retry. */}};const timer=window.setInterval(()=>void poll(),1000);void poll();return()=>{active=false;window.clearInterval(timer)}},[task?.id,task?.status]);
 useEffect(()=>{if(!task||!["completed","completed_with_errors"].includes(task.status))return;let active=true;listPreanalysisDrafts(task.id).then(found=>{if(!active)return;setDrafts(found);setSelectedDrafts(found.presets.map(x=>x.id))}).catch(()=>{});return()=>{active=false}},[task?.id,task?.status]);
 useEffect(()=>setSelected(capabilitiesForFamilies(capabilities,capabilityFamilies(capabilities)).map(x=>x.key)),[capabilities]);
 useEffect(()=>{if(!analysisSelection)return;const text=analysisSelection.selections.map(item=>item.text).join("\n\n");const compatible=capabilities.filter(item=>capabilitySupportsAnalysisText(item,text));setAnalysisScope("selection");setAnalysisItems(analysisSelection.selections);setAnalysisText(text);setSelected(capabilitiesForFamilies(compatible,capabilityFamilies(compatible)).map(item=>item.key));setDrafts(undefined);setAnalysisOpen(true)},[analysisSelection?.requestId]);
 useEffect(()=>{if(analysisScope!=="selection"||!analysisText.trim())return;const compatible=new Set(selectionCapabilities.map(item=>item.key));setSelected(current=>{const filtered=current.filter(key=>compatible.has(key));return filtered.length?filtered:selectionCapabilities.map(item=>item.key)})},[analysisScope,analysisText,selectionCapabilities]);
 const counts=useMemo(()=>presets.reduce<Record<string,number>>((out,row)=>{const family=capabilityFamily(row.capability_key);out[family]=(out[family]||0)+1;return out},{}),[presets]);
 const visible=filter==="all"?presets:presets.filter(row=>capabilityFamily(row.capability_key)===filter);
 const visibleIds=visible.map(row=>row.id); const visibleSelected=visibleIds.filter(id=>selectedPresets.includes(id));
 const allVisibleSelected=visibleIds.length>0&&visibleSelected.length===visibleIds.length;
 const openCreate=()=>{form.resetFields();form.setFieldsValue({capability_family:families[0]});setEditor({open:true})};
 const openEdit=(preset:LearningPreset)=>{form.setFieldsValue({capability_family:capabilityFamily(preset.capability_key),key:preset.normalized_key,...parseValue(preset.value_json)});setEditor({open:true,preset})};
 const save=async()=>{const values=await form.validateFields();const capability=editor.preset?capabilityMap.get(editor.preset.capability_key):chooseFamilyCapability(capabilities,values.capability_family,values.key);if(!capability)return;const content=Object.fromEntries(capability.fields.map(field=>[field.key,values[field.key]]).filter(([,value])=>value!==undefined&&value!==""));if(editor.preset)await updateLearningPreset(editor.preset.id,content,editor.preset.priority);else await putLearningPreset({scope_type:"document",scope_id:documentId,document_revision:revision||"",capability_key:capability.key,key:values.key,value:content,origin:"user"});message.success(t("common.saveSuccess"));setEditor({open:false});await load()};
 const remove=async(id:string)=>{await deleteLearningPreset(id);message.success(t("common.success"));await load()};
 const removeMany=async(ids:string[])=>{if(!ids.length)return;setDeleting(true);try{const results=await Promise.allSettled(ids.map(id=>deleteLearningPreset(id)));const deletedIds=ids.filter((_,index)=>results[index].status==="fulfilled");const failed=ids.length-deletedIds.length;setSelectedPresets(current=>current.filter(id=>!deletedIds.includes(id)));await load();if(failed)message.warning(t("learning.batchDeletePartial",{deleted:deletedIds.length,failed}));else message.success(t("learning.batchDeleteSuccess",{count:deletedIds.length}))}finally{setDeleting(false)}};
 const confirmRemoveMany=(ids:string[],all=false)=>Modal.confirm({title:t(all?"learning.deleteAllPresetConfirm":"learning.batchDeletePresetConfirm",{count:ids.length}),content:t("learning.deletePresetsWarning"),okText:t("common.delete"),okButtonProps:{danger:true},cancelText:t("common.cancel"),onOk:()=>removeMany(ids)});
 const analyze=async()=>{const items=analysisScope==="selection"?analysisItems.map(item=>({text:item.text,context:item.context||item.text,page:item.page})):undefined;setAnalysisOpen(false);setStarting(true);setDrafts(undefined);try{const created=await createPreanalysisTask({dataset_id:datasetId,document_id:documentId,document_revision:revision,capability_keys:selected,analysis_direction:analysisDirection.trim()||undefined,items:items?.length?items:undefined});setTask(created);await runPreanalysisTask(created.id)}catch(e){setTask(undefined);message.error(getLocalizedErrorMessage(e))}finally{setStarting(false)}};
 const stopAnalysis=async()=>{if(!task)return;setStopping(true);try{setTask(await cancelPreanalysisTask(task.id));message.success(t("learning.preanalysisCanceled"))}catch(e){message.error(getLocalizedErrorMessage(e))}finally{setStopping(false)}};
 const confirmStopAnalysis=()=>Modal.confirm({title:t("learning.cancelPreanalysisConfirm"),okText:t("learning.stopAnalysis"),okButtonProps:{danger:true},cancelText:t("common.cancel"),onOk:stopAnalysis});
 const publish=async()=>{if(!task||!drafts||!selectedDrafts.length)return;setPublishing(true);try{await publishPreanalysisDrafts(task.id,revision||"",selectedDrafts,[]);const remaining=await listPreanalysisDrafts(task.id);setDrafts(remaining);setSelectedDrafts(remaining.presets.map(item=>item.id));message.success(t("learning.preanalysisPublished"));await load()}catch(e){message.error(getLocalizedErrorMessage(e))}finally{setPublishing(false)}};
 const editingFamily=Form.useWatch("capability_family",form) as CapabilityFamily|undefined;
 const editingKey=Form.useWatch("key",form) as string|undefined;
 const editingCapability=editor.preset?capabilityMap.get(editor.preset.capability_key):editingFamily?chooseFamilyCapability(capabilities,editingFamily,editingKey||""):undefined;
 return <div className="document-analysis">
  {!localAvailable?<Alert type="warning" showIcon message={t("vocabulary.localOnlyDesktop")}/>:null}
  <div className="document-analysis__header"><div><Typography.Text type="secondary">{t("learning.quickReferenceHint")}</Typography.Text></div><Space align="start"><div className="document-analysis__analysis-action"><div className="document-analysis__analysis-buttons"><Dropdown.Button icon={<DownOutlined/>} menu={{items:[{key:"paragraphs",label:t("learning.generateSelectedParagraphs"),onClick:()=>onRequestParagraphSelection?.()}]}} disabled={!localAvailable||taskActive} loading={starting} onClick={()=>{setAnalysisScope("document");setSelected(capabilitiesForFamilies(capabilities,families).map(item=>item.key));setAnalysisOpen(true)}}><RobotOutlined/>{t("learning.aiGenerateQuickReference")}</Dropdown.Button>{taskActive&&task?.id?<Button danger icon={<StopOutlined/>} loading={stopping} onClick={confirmStopAnalysis}>{t("learning.stopAnalysis")}</Button>:null}</div>{task||starting?<Typography.Text type="secondary" className="document-analysis__status">{task?t("learning.preanalysisStatus",{status:task.status,completed:task.completed,failed:task.failed}):t("learning.analysisPreparing")}</Typography.Text>:null}{task?.error_message?<Typography.Paragraph type="danger" className="document-analysis__error" ellipsis={{rows:3,expandable:true,symbol:t("common.expand")}}>{t("learning.preanalysisFailureDetail",{reason:task.error_message})}</Typography.Paragraph>:null}</div><Button type="primary" icon={<PlusOutlined/>} disabled={!localAvailable} onClick={openCreate}>{t("learning.addQuickReferenceItem")}</Button></Space></div>
  {drafts?.presets.length?<section className="document-analysis__pending"><div className="document-analysis__pending-header"><div><Typography.Title level={5}>{t("learning.pendingAnswers",{count:drafts.presets.length})}</Typography.Title><Typography.Text type="secondary">{t("learning.pendingAnswersHint")}</Typography.Text></div><Button type="primary" loading={publishing} disabled={!selectedDrafts.length} onClick={()=>void publish()}>{t("learning.confirmSelected",{count:selectedDrafts.length})}</Button></div><Checkbox indeterminate={selectedDrafts.length>0&&selectedDrafts.length<drafts.presets.length} checked={selectedDrafts.length===drafts.presets.length} onChange={event=>setSelectedDrafts(event.target.checked?drafts.presets.map(item=>item.id):[])}>{t("common.selectAll")}</Checkbox><List className="document-analysis__drafts" dataSource={drafts.presets} renderItem={item=><List.Item><Checkbox checked={selectedDrafts.includes(item.id)} onChange={event=>setSelectedDrafts(current=>event.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}><Typography.Text strong>{displayPresetKey(item.normalized_key)}</Typography.Text><Tag>{capabilityLabel(item.capability_key)}</Tag>{presetValue(item)}</Checkbox></List.Item>}/></section>:null}
  <Segmented className="document-analysis__filters" value={filter} onChange={value=>setFilter(String(value))} options={[{value:"all",label:`${t("common.all")} ${presets.length}`},...families.filter(family=>counts[family]).map(family=>({value:family,label:`${t(capabilityFamilyI18nKey(family))} ${counts[family]}`}))]}/>
  {presets.length?<div className="document-analysis__bulk-actions"><Checkbox checked={allVisibleSelected} indeterminate={visibleSelected.length>0&&!allVisibleSelected} onChange={event=>setSelectedPresets(current=>event.target.checked?Array.from(new Set([...current,...visibleIds])):current.filter(id=>!visibleIds.includes(id)))}>{t("learning.selectVisible",{count:visibleSelected.length})}</Checkbox><Space><Button danger disabled={!selectedPresets.length||deleting} loading={deleting} onClick={()=>confirmRemoveMany(selectedPresets)}>{t("learning.batchDelete",{count:selectedPresets.length})}</Button><Button danger disabled={deleting} onClick={()=>confirmRemoveMany(presets.map(item=>item.id),true)}>{t("learning.deleteAll")}</Button></Space></div>:null}
  <Spin spinning={loading}><List className="document-analysis__list" dataSource={visible} locale={{emptyText:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={t("learning.noPresetAnswers")}/>}} renderItem={item=><List.Item actions={[<Button key="edit" type="text" icon={<EditOutlined/>} aria-label={t("common.edit")} onClick={()=>openEdit(item)}/>,<Popconfirm key="delete" title={t("learning.deletePresetConfirm")} onConfirm={()=>void remove(item.id)}><Button type="text" danger icon={<DeleteOutlined/>} aria-label={t("common.delete")}/></Popconfirm>]}><Checkbox className="document-analysis__item-checkbox" aria-label={t("learning.selectPreset",{name:displayPresetKey(item.normalized_key)})} checked={selectedPresets.includes(item.id)} onChange={event=>setSelectedPresets(current=>event.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/><List.Item.Meta title={<Space><Typography.Text strong>{displayPresetKey(item.normalized_key)}</Typography.Text><Tag>{capabilityLabel(item.capability_key)}</Tag></Space>} description={<>{presetValue(item)}<Typography.Text type="secondary" className="document-analysis__origin">{item.origin==="user"?t("learning.manuallyAdded"):t("learning.aiGenerated")}</Typography.Text></>}/></List.Item>}/></Spin>
  <Modal open={editor.open} title={editor.preset?t("learning.editQuickReferenceItem"):t("learning.addQuickReferenceItem")} onCancel={()=>setEditor({open:false})} onOk={()=>void save()} okText={t("common.save")} destroyOnHidden><Form form={form} layout="vertical"><Form.Item name="capability_family" label={t("learning.capabilityLabel")} rules={[{required:true}]}><Select disabled={!!editor.preset} options={families.map(family=>({value:family,label:t(capabilityFamilyI18nKey(family))}))}/></Form.Item><Form.Item name="key" label={t("learning.queryContent")} extra={t("learning.queryContentHint")} rules={[{required:true}]}><Input disabled={!!editor.preset}/></Form.Item>{editingCapability?.fields.map(field=><Form.Item key={field.key} name={field.key} label={t(field.label_i18n_key)} rules={field.required?[{required:true,message:t("learning.requiredField")}]:undefined}>{field.type==="string_list"?<Select mode="tags" tokenSeparators={[",","，"]}/>:field.type==="text"?<Input.TextArea rows={4}/>:<Input/>}</Form.Item>)}</Form></Modal>
  <Modal open={analysisOpen} title={t("learning.quickReferenceAiTitle")} width={720} onCancel={()=>setAnalysisOpen(false)} footer={null}>
   <div className="document-analysis__generator"><RobotOutlined/><Typography.Title level={5}>{t("learning.chooseQuickReferenceCapabilities")}</Typography.Title><Typography.Text type="secondary">{t("learning.chooseAnalysisCapabilitiesHint")}</Typography.Text><label>{t("learning.analysisScope")}</label><Typography.Text strong>{t(analysisScope==="selection"?"learning.selectedParagraphs":"learning.wholeDocument")}</Typography.Text>{analysisScope==="selection"?<><Input.TextArea value={analysisText} readOnly autoSize={{minRows:4,maxRows:10}}/><Typography.Text type="secondary">{t("learning.selectedParagraphsReadonlyHint")}</Typography.Text>{analysisText.trim()&&!selectionCapabilities.length?<Alert type="warning" showIcon message={t("learning.noCompatibleAnalysisCapabilities")}/>:null}</>:null}<label>{t("learning.analysisCapabilities")}</label><Select mode="multiple" value={Array.from(new Set(selected.map(key=>capabilityFamily(key))))} onChange={(values:CapabilityFamily[])=>{const source=analysisScope==="selection"?selectionCapabilities:capabilities;setSelected(capabilitiesForFamilies(source,values).map(item=>item.key))}} options={capabilityFamilies(analysisScope==="selection"?selectionCapabilities:capabilities).map(family=>({value:family,label:t(capabilityFamilyI18nKey(family))}))}/><label>{t("learning.analysisDirection")}</label><Input.TextArea value={analysisDirection} onChange={event=>setAnalysisDirection(event.target.value)} autoSize={{minRows:2,maxRows:5}} maxLength={1000} showCount placeholder={t("learning.analysisDirectionPlaceholder")}/><Button type="primary" disabled={!selected.length||(analysisScope==="selection"&&!analysisText.trim())} onClick={()=>void analyze()}>{t("learning.startGenerate")}</Button></div>
  </Modal>
 </div>
}
