// Additional stable API errors discovered by the Core handler audit.

package common

import (
	"net/http"
	"regexp"
	"strings"
	"unicode"
)

func init() {
	registerAdditionalError("MCP authorization required; reconnect this service in settings", http.StatusConflict, 2003103)
	registerAdditionalError("MCP authorization service unavailable", http.StatusServiceUnavailable, 2003104)
	registerAdditionalError("MCP connection failed; reconnect this service if authorization has expired", http.StatusBadGateway, 2003105)
	registerAdditionalError("MCP tool call failed; reconnect this service if authorization has expired", http.StatusBadGateway, 2003106)
	registerAdditionalError("read MCP event stream", http.StatusBadGateway, 2003107)
	registerAdditionalError("LazyMind Cloud login is required", http.StatusUnauthorized, 2002920)
	registerAdditionalError("executor unauthorized", http.StatusUnauthorized, 2001596)
	registerAdditionalError("model config unavailable", http.StatusServiceUnavailable, 2001597)
	registerAdditionalError("invalid task event", http.StatusBadRequest, 2001598)
	registerAdditionalError("persist task event failed", http.StatusServiceUnavailable, 2001599)
	registerAdditionalError("required output missing", http.StatusUnprocessableEntity, 2001600)
	registerAdditionalError("review session has no answers", http.StatusUnprocessableEntity, 2002500)
	registerAdditionalError("default wordbook cannot be deleted", http.StatusConflict, 2002501)
	registerAdditionalError("target wordbook must be different", http.StatusBadRequest, 2002502)
	registerAdditionalError("word_id is required", http.StatusBadRequest, 2002600)
	registerAdditionalError("score must be between 0 and 1", http.StatusBadRequest, 2002601)
	registerAdditionalError("vocabulary review answer does not match the pending card", http.StatusConflict, 2002602)
	registerAdditionalError("vocabulary review answer is incomplete", http.StatusBadRequest, 2002603)
	registerAdditionalError("vocabulary review answer does not match the active session", http.StatusConflict, 2002604)
	registerAdditionalError("vocabulary review session changed while recording answers", http.StatusConflict, 2002605)
	registerAdditionalError("anki system default deck cannot be deleted", http.StatusConflict, 2002606)
	registerAdditionalError("anki deck not found", http.StatusNotFound, 2002607)
	registerAdditionalError("wordbook_id is required", http.StatusBadRequest, 2002608)
	registerAdditionalError("invalid reset scope", http.StatusBadRequest, 2002609)
	registerAdditionalError("word is not sourced from this document", http.StatusNotFound, 2002610)
	registerAdditionalError("word has other sources; remove this document source instead", http.StatusConflict, 2002611)
	registerAdditionalError("ask_words requires 1 to 20 target words", http.StatusBadRequest, 2002612)
	registerAdditionalError("target words must be unique and non-empty", http.StatusBadRequest, 2002613)
	registerAdditionalError("target word is not currently available for review", http.StatusConflict, 2002614)
	registerAdditionalError("cloze requires 10 to 20 correct answers", http.StatusBadRequest, 2002615)
	registerAdditionalError("cloze correct answers must be 10 to 20 unique candidate words", http.StatusBadRequest, 2002616)
	registerAdditionalError("cloze requires at least 20 previewed candidate words; call get_review_words with count >= 20", http.StatusBadRequest, 2002617)
	registerAdditionalError("cloze correct answer is not in the previewed candidates", http.StatusBadRequest, 2002618)
	registerAdditionalError("some cloze candidates could not be issued", http.StatusConflict, 2002619)
	registerAdditionalError("mode must be e2c or c2e", http.StatusBadRequest, 2002620)
	registerAdditionalError("question_type must be choice or fill", http.StatusBadRequest, 2002621)
	registerAdditionalError("e2c only supports choice questions", http.StatusBadRequest, 2002622)
	registerAdditionalError("review session has no previewed questions", http.StatusConflict, 2002623)
	registerAdditionalError("review item already answered", http.StatusConflict, 2002624)
	registerAdditionalError("review session still has remaining questions", http.StatusConflict, 2002625)
	registerAdditionalError("processing_level must be stored, parsed, chunked, or indexed", http.StatusBadRequest, 2002642)
	registerAdditionalError("update processing level failed", http.StatusInternalServerError, 2002643)
	registerAdditionalError("create document processing state failed", http.StatusInternalServerError, 2002644)
	registerAdditionalError("removing an embedding model requires confirmation to downgrade all indexed knowledge bases to chunked", http.StatusConflict, 2002645)
	registerAdditionalError("vector rebuild requires indexed processing level", http.StatusBadRequest, 2002646)
	registerAdditionalError("artifact sink requires a database, attempt and slot", http.StatusInternalServerError, 2001993)
	registerAdditionalError("tool config unavailable", http.StatusServiceUnavailable, 2001994)
	registerAdditionalError("advance, retry, and rewind require exactly one target", http.StatusUnprocessableEntity, 2001305)
	registerAdditionalError("algorithm service unavailable", http.StatusBadGateway, 2001306)
	registerAdditionalError("algorithm_id required", http.StatusBadRequest, 2001307)
	registerAdditionalError("aliases must contain word", http.StatusBadRequest, 2001308)
	registerAdditionalError("analysis_id and candidate_id required", http.StatusBadRequest, 2001309)
	registerAdditionalError("another plugin session is active; finish or close it before mentioning a different plugin", http.StatusConflict, 2001310)
	registerAdditionalError("api_key already exists", http.StatusConflict, 2001311)
	registerAdditionalError("api_key is required", http.StatusBadRequest, 2001312)
	registerAdditionalError("api_key is required when using the default base_url", http.StatusBadRequest, 2001313)
	registerAdditionalError("api_key not found", http.StatusNotFound, 2001314)
	registerAdditionalError("at most one plugin mention is allowed per turn", http.StatusBadRequest, 2001315)
	registerAdditionalError("base_url is required", http.StatusBadRequest, 2001316)
	registerAdditionalError("build upstream request failed", http.StatusInternalServerError, 2001317)
	registerAdditionalError("build xlsx template failed", http.StatusInternalServerError, 2001318)
	registerAdditionalError("built-in workflows cannot be modified", http.StatusForbidden, 2001319)
	registerAdditionalError("builtin skill not found", http.StatusNotFound, 2001320)
	registerAdditionalError("cancel running thread failed", http.StatusBadGateway, 2001321)
	registerAdditionalError("candidate not found", http.StatusBadRequest, 2001322)
	registerAdditionalError("candidate_id must include thread_id prefix", http.StatusBadRequest, 2001323)
	registerAdditionalError("candidate_id required", http.StatusBadRequest, 2001324)
	registerAdditionalError("cannot copy directory into its child", http.StatusBadRequest, 2001325)
	registerAdditionalError("cannot move between package root and file path", http.StatusBadRequest, 2001326)
	registerAdditionalError("cannot move directory into its child", http.StatusBadRequest, 2001327)
	registerAdditionalError("cannot write file over directory", http.StatusBadRequest, 2001328)
	registerAdditionalError("cannot write skill root", http.StatusBadRequest, 2001329)
	registerAdditionalError("category cannot be empty", http.StatusBadRequest, 2001330)
	registerAdditionalError("category does not match group", http.StatusBadRequest, 2001331)
	registerAdditionalError("category id required", http.StatusBadRequest, 2001332)
	registerAdditionalError("category is required", http.StatusBadRequest, 2001333)
	registerAdditionalError("category name too long", http.StatusBadRequest, 2001334)
	registerAdditionalError("check existing groups failed", http.StatusInternalServerError, 2001335)
	registerAdditionalError("conflict", http.StatusConflict, 2001336)
	registerAdditionalError("copy requires package-internal paths", http.StatusBadRequest, 2001337)
	registerAdditionalError("create database connection failed", http.StatusInternalServerError, 2001338)
	registerAdditionalError("create failed", http.StatusInternalServerError, 2001339)
	registerAdditionalError("create item failed", http.StatusInternalServerError, 2001340)
	registerAdditionalError("create prompt category failed", http.StatusConflict, 2001341)
	registerAdditionalError("create prompt failed", http.StatusConflict, 2001342)
	registerAdditionalError("create repair run failed", http.StatusInternalServerError, 2001343)
	registerAdditionalError("create upstream thread failed", http.StatusBadGateway, 2001344)
	registerAdditionalError("create word group from conflict failed", http.StatusInternalServerError, 2001345)
	registerAdditionalError("cron_expr and prompt_template are required", http.StatusBadRequest, 2001346)
	registerAdditionalError("custom workflow scripts require administrator permission or a matching deterministic audit", http.StatusForbidden, 2001347)
	registerAdditionalErrorAlias("custom plugin scripts require the administrator publishing workflow", "custom workflow scripts require administrator permission or a matching deterministic audit", http.StatusForbidden, 2001347)
	registerAdditionalError("database connection not found", http.StatusNotFound, 2001348)
	registerAdditionalError("dataset_ids required", http.StatusBadRequest, 2001349)
	registerAdditionalError("db unavailable", http.StatusInternalServerError, 2001350)
	registerAdditionalError("decrypt database password failed", http.StatusInternalServerError, 2001351)
	registerAdditionalError("delete database connection failed", http.StatusInternalServerError, 2001352)
	registerAdditionalError("delete item failed", http.StatusInternalServerError, 2001353)
	registerAdditionalError("delete prompt category failed", http.StatusInternalServerError, 2001354)
	registerAdditionalError("delete prompt failed", http.StatusInternalServerError, 2001355)
	registerAdditionalError("delete scan source failed", http.StatusBadGateway, 2001356)
	registerAdditionalError("delete thread failed", http.StatusInternalServerError, 2001357)
	registerAdditionalError("delete upstream thread failed", http.StatusBadGateway, 2001358)
	registerAdditionalError("description or skill_id is required", http.StatusBadRequest, 2001359)
	registerAdditionalError("diff refs must belong to the same skill", http.StatusUnprocessableEntity, 2001360)
	registerAdditionalError("disable tool failed", http.StatusInternalServerError, 2001361)
	registerAdditionalError("dismiss failed", http.StatusInternalServerError, 2001362)
	registerAdditionalError("display_name/content/category required", http.StatusBadRequest, 2001363)
	registerAdditionalErrorAlias("display_name must be 255 characters or fewer", "Display name is too long", http.StatusBadRequest, 2000614)
	registerAdditionalError("draft has no generated content to repair", http.StatusBadRequest, 2001364)
	registerAdditionalError("draft_id required", http.StatusBadRequest, 2001365)
	registerAdditionalError("draft_version required", http.StatusBadRequest, 2001366)
	registerAdditionalError("duplicate category in selections", http.StatusBadRequest, 2001367)
	registerAdditionalError("embedding model is not ready", http.StatusUnprocessableEntity, 2001368)
	registerAdditionalError("enable tool failed", http.StatusInternalServerError, 2001369)
	registerAdditionalError("enqueue failed", http.StatusInternalServerError, 2001370)
	registerAdditionalError("estimate context usage failed", http.StatusBadGateway, 2001371)
	registerAdditionalError("eval set item not found", http.StatusNotFound, 2001372)
	registerAdditionalError("eval set not found", http.StatusNotFound, 2001373)
	registerAdditionalError("expected_draft_version required", http.StatusBadRequest, 2001374)
	registerAdditionalError("export context prompt failed", http.StatusBadGateway, 2001375)
	registerAdditionalError("failed to create task", http.StatusInternalServerError, 2001376)
	registerAdditionalError("failed to create task conversation", http.StatusInternalServerError, 2001377)
	registerAdditionalError("failed to marshal ext", http.StatusInternalServerError, 2001378)
	registerAdditionalError("fetch thread flow status failed", http.StatusBadGateway, 2001379)
	registerAdditionalError("file exceeds max size", http.StatusBadRequest, 2001380)
	registerAdditionalError("framework tool unavailable", http.StatusConflict, 2001381)
	registerAdditionalError("generation analysis not found", http.StatusNotFound, 2001382)
	registerAdditionalError("group is not selectable without api_key when using the default base_url", http.StatusBadRequest, 2001383)
	registerAdditionalError("group not found in selected providers", http.StatusNotFound, 2001384)
	registerAdditionalError("import task not found", http.StatusNotFound, 2001385)
	registerAdditionalError("internal token required", http.StatusUnauthorized, 2001386)
	registerAdditionalError("invalid category", http.StatusBadRequest, 2001387)
	registerAdditionalError("invalid cron expression", http.StatusBadRequest, 2001388)
	registerAdditionalError("invalid cron_expr", http.StatusBadRequest, 2001389)
	registerAdditionalError("invalid eval_set_id", http.StatusBadRequest, 2001390)
	registerAdditionalError("invalid import_token", http.StatusBadRequest, 2001391)
	registerAdditionalError("invalid merge item", http.StatusBadRequest, 2001392)
	registerAdditionalError("invalid repair mode", http.StatusBadRequest, 2001393)
	registerAdditionalError("invalid repair target", http.StatusBadRequest, 2001394)
	registerAdditionalError("invalid resource_type", http.StatusBadRequest, 2001395)
	registerAdditionalError("invalid scope", http.StatusBadRequest, 2001396)
	registerAdditionalError("invalid sort", http.StatusBadRequest, 2001397)
	registerAdditionalError("invalid start command", http.StatusBadRequest, 2001398)
	registerAdditionalError("invalid start plan", http.StatusBadRequest, 2001399)
	registerAdditionalError("invalid task_id", http.StatusBadRequest, 2001400)
	registerAdditionalError("invalid transition command", http.StatusBadRequest, 2001401)
	registerAdditionalError("item_id required", http.StatusBadRequest, 2001402)
	registerAdditionalError("list mcp servers failed", http.StatusInternalServerError, 2001403)
	registerAdditionalError("list provider groups failed", http.StatusInternalServerError, 2001404)
	registerAdditionalError("load chat runtime config failed", http.StatusInternalServerError, 2001405)
	registerAdditionalError("load llm config failed", http.StatusInternalServerError, 2001406)
	registerAdditionalError("load local fs chat paths failed", http.StatusInternalServerError, 2001407)
	registerAdditionalError("lock failed", http.StatusInternalServerError, 2001408)
	registerAdditionalError("marshal thread payload failed", http.StatusInternalServerError, 2001409)
	registerAdditionalError("mcp server not found", http.StatusNotFound, 2001410)
	registerAdditionalError("memory review result not found", http.StatusNotFound, 2001411)
	registerAdditionalError("merges is required", http.StatusBadRequest, 2001412)
	registerAdditionalError("metadata field required", http.StatusBadRequest, 2001413)
	registerAdditionalError("missing builtin_skill_uid", http.StatusBadRequest, 2001414)
	registerAdditionalError("missing connection", http.StatusBadRequest, 2001415)
	registerAdditionalError("missing market_item_id", http.StatusBadRequest, 2001416)
	registerAdditionalError("missing review_id", http.StatusBadRequest, 2001417)
	registerAdditionalErrorAlias("missing revision_id", "revision_id required", http.StatusBadRequest, 2001509)
	registerAdditionalErrorAlias("missing task_id", "task_id is required", http.StatusBadRequest, 2001537)
	registerAdditionalError("missing version_id", http.StatusBadRequest, 2001420)
	registerAdditionalError("model not found in selected models", http.StatusNotFound, 2001421)
	registerAdditionalError("move requires skill paths", http.StatusBadRequest, 2001422)
	registerAdditionalError("multimodal embedding model is not ready", http.StatusUnprocessableEntity, 2001423)
	registerAdditionalError("name cannot be empty", http.StatusBadRequest, 2001424)
	registerAdditionalErrorAlias("name is required", "name required", http.StatusBadRequest, 2000860)
	registerAdditionalError("name/category required", http.StatusBadRequest, 2001426)
	registerAdditionalError("no internal skills selected", http.StatusBadRequest, 2001427)
	registerAdditionalError("no slot binding", http.StatusBadRequest, 2001428)
	registerAdditionalError("no valid fields to update", http.StatusBadRequest, 2001429)
	registerAdditionalError("normalize upload text encoding failed", http.StatusBadRequest, 2001430)
	registerAdditionalError("not found", http.StatusNotFound, 2001431)
	registerAdditionalError("operation must be advance, execute, execute_batch, retry, or rewind", http.StatusUnprocessableEntity, 2001432)
	registerAdditionalError("order lookup failed", http.StatusInternalServerError, 2001433)
	registerAdditionalError("order_version conflict; refresh and retry", http.StatusConflict, 2001434)
	registerAdditionalError("overwrite is not supported", http.StatusBadRequest, 2001435)
	registerAdditionalError("parent directory does not exist", http.StatusBadRequest, 2001436)
	registerAdditionalError("patch item failed", http.StatusInternalServerError, 2001437)
	registerAdditionalError("path is a directory", http.StatusBadRequest, 2001438)
	registerAdditionalErrorAlias("path is required", "Path is required", http.StatusBadRequest, 2000209)
	registerAdditionalError("path must include category and skill name", http.StatusBadRequest, 2001440)
	registerAdditionalError("path must start with skills", http.StatusBadRequest, 2001441)
	registerAdditionalError("permanent delete requires permanent=true and confirm=true", http.StatusBadRequest, 2001442)
	registerAdditionalError("persist search_config failed", http.StatusInternalServerError, 2001443)
	registerAdditionalError("personal resource generate failed", http.StatusBadGateway, 2001444)
	registerAdditionalError("plugin draft has no changes from its base revision", http.StatusConflict, 2001445)
	registerAdditionalError("plugin draft not found", http.StatusNotFound, 2001446)
	registerAdditionalError("plugin id already exists for this user", http.StatusConflict, 2001447)
	registerAdditionalError("plugin not found", http.StatusNotFound, 2001448)
	registerAdditionalError("plugin validation failed", http.StatusUnprocessableEntity, 2001449)
	registerAdditionalError("workflow.yaml id required", http.StatusBadRequest, 2001450)
	registerAdditionalError("workflow_id is required", http.StatusUnprocessableEntity, 2001451)
	registerAdditionalErrorAlias("workflow_id required", "workflow_id is required", http.StatusBadRequest, 2001451)
	registerAdditionalError("workflow_mode must be 'auto' or 'dynamic'", http.StatusBadRequest, 2001453)
	registerAdditionalError("polish failed", http.StatusInternalServerError, 2001454)
	registerAdditionalError("post thread action failed", http.StatusBadGateway, 2001455)
	registerAdditionalError("prepare chat attachments failed", http.StatusBadGateway, 2001456)
	registerAdditionalError("preset prompt is read only", http.StatusForbidden, 2001457)
	registerAdditionalError("preview eval set import failed", http.StatusInternalServerError, 2001458)
	registerAdditionalError("project session failed", http.StatusUnprocessableEntity, 2001459)
	registerAdditionalError("prompt category already exists", http.StatusConflict, 2001460)
	registerAdditionalError("prompt category not found", http.StatusNotFound, 2001461)
	registerAdditionalError("prompt polish failed", http.StatusBadGateway, 2001462)
	registerAdditionalError("provider_name and base_url are required", http.StatusBadRequest, 2001463)
	registerAdditionalError("proxy evo request failed", http.StatusBadGateway, 2001464)
	registerAdditionalError("publish failed", http.StatusInternalServerError, 2001465)
	registerAdditionalError("query active session failed", http.StatusInternalServerError, 2001466)
	registerAdditionalError("query artifacts failed", http.StatusInternalServerError, 2001467)
	registerAdditionalError("query conversation artifacts failed", http.StatusInternalServerError, 2001468)
	registerAdditionalError("query conversation failed", http.StatusInternalServerError, 2001469)
	registerAdditionalError("query database connection failed", http.StatusInternalServerError, 2001470)
	registerAdditionalError("query database connections failed", http.StatusInternalServerError, 2001471)
	registerAdditionalError("query dataset usage failed", http.StatusInternalServerError, 2002310)
	registerAdditionalError("query disabled tools failed", http.StatusInternalServerError, 2001472)
	registerAdditionalError("query failed", http.StatusInternalServerError, 2001473)
	registerAdditionalError("query group models failed", http.StatusInternalServerError, 2001474)
	registerAdditionalError("query latest session failed", http.StatusInternalServerError, 2001475)
	registerAdditionalError("query local fs chat setting failed", http.StatusInternalServerError, 2001476)
	registerAdditionalError("query memory review result failed", http.StatusInternalServerError, 2001477)
	registerAdditionalError("query memory review results failed", http.StatusInternalServerError, 2001478)
	registerAdditionalError("query order failed", http.StatusInternalServerError, 2001479)
	registerAdditionalError("query prompt categories failed", http.StatusInternalServerError, 2001480)
	registerAdditionalError("query prompt states failed", http.StatusInternalServerError, 2001481)
	registerAdditionalError("query prompt usage failed", http.StatusInternalServerError, 2001482)
	registerAdditionalError("query resource version failed", http.StatusInternalServerError, 2001483)
	registerAdditionalError("query resource versions failed", http.StatusInternalServerError, 2001484)
	registerAdditionalError("query selected providers failed", http.StatusInternalServerError, 2001485)
	registerAdditionalError("query session failed", http.StatusInternalServerError, 2001486)
	registerAdditionalError("query sessions failed", http.StatusInternalServerError, 2001487)
	registerAdditionalError("query skill review summary failed", http.StatusInternalServerError, 2001488)
	registerAdditionalError("query slots failed", http.StatusInternalServerError, 2001489)
	registerAdditionalError("query steps failed", http.StatusInternalServerError, 2001490)
	registerAdditionalError("query subagent artifacts failed", http.StatusInternalServerError, 2001491)
	registerAdditionalError("query task artifacts failed", http.StatusInternalServerError, 2001492)
	registerAdditionalError("query task failed", http.StatusInternalServerError, 2001493)
	registerAdditionalError("query uploaded files failed", http.StatusInternalServerError, 2001494)
	registerAdditionalError("query user preference status failed", http.StatusInternalServerError, 2001495)
	registerAdditionalError("query user ui preferences failed", http.StatusInternalServerError, 2001496)
	registerAdditionalError("query verified provider failed", http.StatusInternalServerError, 2001497)
	registerAdditionalError("query versions failed", http.StatusInternalServerError, 2001498)
	registerAdditionalError("read events failed", http.StatusInternalServerError, 2001499)
	registerAdditionalError("record prompt usage failed", http.StatusInternalServerError, 2001500)
	registerAdditionalError("reload failed", http.StatusInternalServerError, 2001501)
	registerAdditionalError("reorder failed", http.StatusInternalServerError, 2001502)
	registerAdditionalError("repair in progress, please wait", http.StatusConflict, 2001503)
	registerAdditionalError("repair run not found", http.StatusNotFound, 2001504)
	registerAdditionalError("repair stale draft", http.StatusConflict, 2001505)
	registerAdditionalError("reserve transition command failed", http.StatusServiceUnavailable, 2001506)
	registerAdditionalError("resource version not found", http.StatusNotFound, 2001507)
	registerAdditionalError("restore failed", http.StatusInternalServerError, 2001508)
	registerAdditionalError("revision_id required", http.StatusBadRequest, 2001509)
	registerAdditionalError("rollback failed", http.StatusInternalServerError, 2001510)
	registerAdditionalError("run skill review failed", http.StatusInternalServerError, 2001511)
	registerAdditionalError("save failed", http.StatusInternalServerError, 2001512)
	registerAdditionalError("save selected provider failed", http.StatusInternalServerError, 2001513)
	registerAdditionalError("schedule not found", http.StatusNotFound, 2001514)
	registerAdditionalError("schedule_id required", http.StatusBadRequest, 2001515)
	registerAdditionalError("search_config required", http.StatusBadRequest, 2001516)
	registerAdditionalError("select revision failed", http.StatusInternalServerError, 2001517)
	registerAdditionalError("session is dismissed", http.StatusConflict, 2001518)
	registerAdditionalError("session not found", http.StatusNotFound, 2001519)
	registerAdditionalError("session not found or already dismissed", http.StatusNotFound, 2001520)
	registerAdditionalError("session step not found", http.StatusNotFound, 2001521)
	registerAdditionalError("session_id and slot_id required", http.StatusBadRequest, 2001522)
	registerAdditionalError("session_id, slot_id and list_index required", http.StatusBadRequest, 2001523)
	registerAdditionalError("share item is not pending", http.StatusConflict, 2001524)
	registerAdditionalError("skill draft not initialized", http.StatusInternalServerError, 2001525)
	registerAdditionalError("skill generate returned empty content", http.StatusBadGateway, 2001526)
	registerAdditionalError("skill must be in trash before permanent delete", http.StatusBadRequest, 2001527)
	registerAdditionalError("skill organize call failed", http.StatusBadGateway, 2001528)
	registerAdditionalError("skill organize returned unexpected response", http.StatusBadGateway, 2001529)
	registerAdditionalError("slot has no existing items; cannot infer slot", http.StatusBadRequest, 2001530)
	registerAdditionalError("slot revision not found", http.StatusNotFound, 2001531)
	registerAdditionalError("source analysis not found", http.StatusBadRequest, 2001532)
	registerAdditionalError("target revision not found", http.StatusNotFound, 2001533)
	registerAdditionalError("target_fields is required", http.StatusBadRequest, 2001534)
	registerAdditionalError("target_revision_id required", http.StatusBadRequest, 2001535)
	registerAdditionalError("task already in terminal state", http.StatusBadRequest, 2001536)
	registerAdditionalError("task_id is required", http.StatusBadRequest, 2001537)
	registerAdditionalErrorAlias("task_id required", "task_id is required", http.StatusBadRequest, 2001537)
	registerAdditionalError("this provider does not support models", http.StatusBadRequest, 2001539)
	registerAdditionalError("this provider only allows one group per user", http.StatusConflict, 2001540)
	registerAdditionalError("thread_id query is required", http.StatusBadRequest, 2001541)
	registerAdditionalError("tool cannot be disabled", http.StatusBadRequest, 2001542)
	registerAdditionalError("tool not found", http.StatusNotFound, 2001543)
	registerAdditionalError("tool_name required", http.StatusBadRequest, 2001544)
	registerAdditionalError("too many dataset_ids", http.StatusBadRequest, 2002311)
	registerAdditionalError("transition command not found", http.StatusNotFound, 2001545)
	registerAdditionalError("trash requires a skill package root", http.StatusBadRequest, 2001546)
	registerAdditionalError("unsafe path", http.StatusBadRequest, 2001547)
	registerAdditionalError("unsupported file_type", http.StatusBadRequest, 2001548)
	registerAdditionalError("unsupported for personal resource", http.StatusUnprocessableEntity, 2001549)
	registerAdditionalError("update api_key failed", http.StatusInternalServerError, 2001550)
	registerAdditionalError("update caption failed", http.StatusInternalServerError, 2001551)
	registerAdditionalError("update database connection check result failed", http.StatusInternalServerError, 2001552)
	registerAdditionalError("update database connection failed", http.StatusInternalServerError, 2001553)
	registerAdditionalError("update favorite failed", http.StatusInternalServerError, 2001554)
	registerAdditionalError("update local fs chat setting failed", http.StatusInternalServerError, 2001555)
	registerAdditionalError("update prompt failed", http.StatusConflict, 2001556)
	registerAdditionalError("update share failed", http.StatusInternalServerError, 2001557)
	registerAdditionalError("update skill organize reservation failed", http.StatusInternalServerError, 2001558)
	registerAdditionalError("update slot failed", http.StatusInternalServerError, 2001559)
	registerAdditionalError("update user ui preferences failed", http.StatusInternalServerError, 2001560)
	registerAdditionalError("upload belongs to another user", http.StatusForbidden, 2001561)
	registerAdditionalError("upload is not completed", http.StatusBadRequest, 2001562)
	registerAdditionalError("upstream error", http.StatusBadGateway, 2001563)
	registerAdditionalError("upstream request failed", http.StatusBadGateway, 2001564)
	registerAdditionalError("user not found", http.StatusUnauthorized, 2001565)
	registerAdditionalErrorAlias("user_id is required", "user_id required", http.StatusUnauthorized, 2000900)
	registerAdditionalError("user_preference metadata is only supported for user_preference", http.StatusBadRequest, 2001567)
	registerAdditionalError("value must not be empty", http.StatusBadRequest, 2001568)
	registerAdditionalError("verification failed", http.StatusBadGateway, 2001569)
	registerAdditionalError("version conflict", http.StatusConflict, 2001570)
	registerAdditionalError("version not found", http.StatusNotFound, 2001571)
	registerAdditionalError("version required", http.StatusBadRequest, 2001572)
	registerAdditionalError("workflow confirmation stale", http.StatusConflict, 2001573)
	registerAdditionalError("write slot revision failed", http.StatusInternalServerError, 2001574)
	registerAdditionalError("无法查询 skill 维护任务状态", http.StatusServiceUnavailable, 2001575)
	registerAdditionalError("请先配置 llm 和 evo_llm 模型后再创建任务", http.StatusUnprocessableEntity, 2001576)

	// systemdeps / local ffmpeg dependency management
	registerAdditionalError("local runtime root is not configured", http.StatusServiceUnavailable, 2001577)
	registerAdditionalError("load ffmpeg dependency status failed", http.StatusInternalServerError, 2001578)
	registerAdditionalError("ffmpeg dependency settings are only supported in local/desktop runtime", http.StatusForbidden, 2001579)
	registerAdditionalError("source must be custom or bundled", http.StatusBadRequest, 2001580)
	registerAdditionalError("customPath is required when source is custom", http.StatusBadRequest, 2001581)
	registerAdditionalError("bundled ffmpeg install is only supported in local/desktop runtime", http.StatusForbidden, 2001582)
	registerAdditionalError("runtime root is not configured", http.StatusServiceUnavailable, 2001583)
	registerAdditionalError("ffmpeg executable not found", http.StatusBadRequest, 2001584)
	registerAdditionalError("ffprobe was not found next to the selected ffmpeg binary", http.StatusBadRequest, 2001585)
	registerAdditionalError("extract ffmpeg download failed", http.StatusBadRequest, 2001586)
	registerAdditionalError("downloaded ffmpeg archives did not contain ffmpeg and ffprobe binaries", http.StatusBadRequest, 2001587)
	registerAdditionalError("ffmpeg install finished but binaries were not detected", http.StatusInternalServerError, 2001588)
	registerAdditionalError("ffmpeg download failed", http.StatusBadGateway, 2001589)
	registerAdditionalError("write ffmpeg download failed", http.StatusInternalServerError, 2001590)
	registerAdditionalError("unsupported ffmpeg archive format", http.StatusBadRequest, 2001591)
	registerAdditionalErrorPattern("bundled ffmpeg install is not supported on %s/%s", "bundled ffmpeg install is not supported on this platform", http.StatusBadRequest, 2001592)
	registerAdditionalErrorPattern("downloaded %s binary could not run", "downloaded ffmpeg binary could not run", http.StatusInternalServerError, 2001593)
	registerAdditionalError("ffmpeg download checksum mismatch", http.StatusBadGateway, 2001594)
	registerAdditionalError("workflow session has no pinned public revision", http.StatusUnprocessableEntity, 2001595)

	// Workflow and hosted external Agent errors.
	registerAdditionalError("at most one workflow mention is allowed per turn", http.StatusBadRequest, 2002022)
	registerAdditionalError("resolve conversation workflow binding failed", http.StatusInternalServerError, 2002023)
	registerAdditionalError("another workflow session is active; finish or close it before mentioning a different workflow", http.StatusConflict, 2002024)
	registerAdditionalError("invalid agent invocation", http.StatusBadRequest, 2002025)
	registerAdditionalError("agent invocation not found", http.StatusNotFound, 2002026)
	registerAdditionalError("agent invocation conflicts with an existing record", http.StatusConflict, 2002027)
	registerAdditionalError("task is terminal", http.StatusConflict, 2002049)
	registerAdditionalError("chat_executor must be 'lazymind', 'codex', 'cursor', or 'workbuddy'", http.StatusBadRequest, 2002050)
	registerAdditionalErrorAlias("assistant must be 'lazymind', 'codex', 'cursor', or 'workbuddy'", "chat_executor must be 'lazymind', 'codex', 'cursor', or 'workbuddy'", http.StatusBadRequest, 2002050)
	registerAdditionalErrorAlias("assistants contains an unsupported chat executor", "chat_executor must be 'lazymind', 'codex', 'cursor', or 'workbuddy'", http.StatusBadRequest, 2002050)
	registerAdditionalError("conversation has an unsupported chat executor", http.StatusConflict, 2002051)
	registerAdditionalError("external chat executors require streaming", http.StatusConflict, 2002052)
	registerAdditionalError("unsupported external chat provider", http.StatusBadRequest, 2002053)
	registerAdditionalErrorAlias("invalid external Agent session catalog", "Invalid request", http.StatusBadRequest, 2000103)
	registerAdditionalError("valid provider and host_id are required", http.StatusBadRequest, 2002054)
	registerAdditionalError("host_id and lease_token are required", http.StatusBadRequest, 2002055)
	registerAdditionalError("host_id, lease_token and event_id are required", http.StatusBadRequest, 2002056)
	registerAdditionalError("unsupported external chat event", http.StatusBadRequest, 2002057)
	registerAdditionalError("external chat lease is no longer owned by this host", http.StatusConflict, 2002058)
	registerAdditionalError("external chat event_id conflicts with an existing event", http.StatusConflict, 2002059)
	registerAdditionalError("external chat store is unavailable", http.StatusServiceUnavailable, 2002060)
	registerAdditionalError("unsupported chat executor", http.StatusBadRequest, 2002061)
	registerAdditionalError("external chat requires an authenticated user", http.StatusUnauthorized, 2002062)
	registerAdditionalErrorPattern("%s Agent host is offline; start `lazymind agent host run` and retry", "External Agent host is offline", http.StatusServiceUnavailable, 2002063)
	registerAdditionalError("create external chat run", http.StatusInternalServerError, 2002064)
	registerAdditionalError("external Agent failed", http.StatusBadGateway, 2002065)
	registerAdditionalError("host_id is too long", http.StatusBadRequest, 2002066)
	registerAdditionalError("event_id is too long", http.StatusBadRequest, 2002067)
	registerAdditionalError("stop external chat failed", http.StatusServiceUnavailable, 2002068)
	registerAdditionalErrorPattern("query %s Agent Host", "Query external Agent Host failed", http.StatusServiceUnavailable, 2002069)
	registerAdditionalErrorPattern("%s is unavailable", "External Agent is unavailable", http.StatusServiceUnavailable, 2002070)
	registerAdditionalError("read external chat events", http.StatusServiceUnavailable, 2002071)
	registerAdditionalError("external chat event payload is too large", http.StatusBadRequest, 2002072)
	registerAdditionalError("external Agent lease is invalid or expired", http.StatusConflict, 2002073)
	registerAdditionalError("external chat idempotency key is too long", http.StatusBadRequest, 2002074)
	registerAdditionalErrorAlias("external chat request_id is too long", "external chat idempotency key is too long", http.StatusBadRequest, 2002074)
	registerAdditionalError("external chat idempotency key conflicts with another request", http.StatusConflict, 2002075)
	registerAdditionalError("query external chat idempotency record failed", http.StatusServiceUnavailable, 2002076)
	registerAdditionalError("algorithm chat stream failed", http.StatusBadGateway, 2002077)
	registerAdditionalError("chat service returned no answer", http.StatusBadGateway, 2002078)
	registerAdditionalError("knowledge backend id is empty", http.StatusInternalServerError, 2002079)
	registerAdditionalError("unaligned page token offset", http.StatusBadRequest, 2002080)
	registerAdditionalError("chunk backend business code failed", http.StatusBadGateway, 2002081)
	registerAdditionalError("chunk backend business status failed", http.StatusBadGateway, 2002082)
	registerAdditionalError("chunk backend business success failed", http.StatusBadGateway, 2002083)
	registerAdditionalError("inline artifact content is missing or exceeds 20 mib", http.StatusBadRequest, 2002084)
	registerAdditionalError("inline artifact content is invalid or exceeds 20 mib", http.StatusBadRequest, 2002085)
	registerAdditionalError("inline artifact filename is invalid", http.StatusBadRequest, 2002086)
	registerAdditionalError("inline artifact size does not match content", http.StatusBadRequest, 2002087)
	registerAdditionalError("inline artifact sha256 does not match content", http.StatusBadRequest, 2002088)
	registerAdditionalError("create workflow artifact directory", http.StatusInternalServerError, 2002089)
	registerAdditionalError("encode managed artifact metadata", http.StatusInternalServerError, 2002090)
	registerAdditionalError("managed artifact path is outside lazymind storage", http.StatusInternalServerError, 2002091)
	registerAdditionalError("read managed artifact", http.StatusInternalServerError, 2002092)
	registerAdditionalError("managed artifact exceeds 20 mib", http.StatusInternalServerError, 2002093)
	registerAdditionalError("managed artifact sha256 does not match content", http.StatusInternalServerError, 2002094)
	registerAdditionalError("create managed artifact", http.StatusInternalServerError, 2002095)
	registerAdditionalError("write managed artifact", http.StatusInternalServerError, 2002096)
	registerAdditionalError("commit managed artifact", http.StatusInternalServerError, 2002097)
	registerAdditionalErrorAlias("skill package contains too many entries", "Invalid skill package", http.StatusBadRequest, 2002294)
	registerAdditionalErrorPattern("skill package cannot contain symlink %q", "Invalid skill package", http.StatusBadRequest, 2002294)
	registerAdditionalErrorPattern("skill package contains duplicate path %q", "Invalid skill package", http.StatusBadRequest, 2002294)
	registerAdditionalErrorPattern("skill package file %q exceeds %d bytes", "Invalid skill package", http.StatusBadRequest, 2002294)
	registerAdditionalErrorPattern("skill package exceeds %d uncompressed bytes", "Invalid skill package", http.StatusBadRequest, 2002294)
	registerAdditionalErrorPattern("skill name cannot exceed %d characters", "Skill name cannot exceed 80 characters", http.StatusBadRequest, 2002305)
	registerAdditionalErrorPattern("skill description cannot exceed %d characters", "Skill description cannot exceed 1024 characters", http.StatusBadRequest, 2002306)
	registerAdditionalErrorPattern("github ref lookup failed with http status %d", "Invalid request", http.StatusBadRequest, 2000103)
	registerAdditionalErrorAlias("github ref lookup failed", "Invalid request", http.StatusBadRequest, 2000103)
	registerAdditionalErrorAlias("github ref lookup returned invalid json", "Invalid request", http.StatusBadRequest, 2000103)
	for _, source := range []string{
		"github url must identify a repository",
		"github url must not contain credentials, port, query, or fragment",
		"github url must point to a repository root, direct zip, or /tree/<ref>/<skill-path>",
		"github url contains an invalid path segment",
		"github repository default branch could not be resolved",
		"github url ref could not be resolved",
		"locked github archive ref does not match source url",
		"locked github archive url is invalid",
		"locked github archive url does not match source repository",
		"skillhub url must not contain credentials, port, query, or fragment",
		"skillhub url must point to /skills/<slug> or /skills/<namespace>/<slug>",
		"skillhub url contains an invalid path segment",
	} {
		registerAdditionalErrorAlias(source, "Invalid request", http.StatusBadRequest, 2000103)
	}
	registerAdditionalErrorPattern("skill package must contain skill.md in subdirectory %q", "Invalid skill package", http.StatusBadRequest, 2002294)
	registerAdditionalErrorPattern("skill package download exceeds %d bytes", "Invalid skill package", http.StatusBadRequest, 2002294)

	// Personal recovery and archive lifecycle errors.
	registerAdditionalError("query archive folders failed", http.StatusInternalServerError, 2002098)
	registerAdditionalError("archive folder not found", http.StatusNotFound, 2002099)
	registerAdditionalError("query archive folder failed", http.StatusInternalServerError, 2002100)
	registerAdditionalError("archive conversation failed", http.StatusInternalServerError, 2002101)
	registerAdditionalError("unarchive conversation failed", http.StatusInternalServerError, 2002102)
	registerAdditionalError("archived conversation not found", http.StatusNotFound, 2002103)
	registerAdditionalError("restore conversation failed", http.StatusInternalServerError, 2002104)
	registerAdditionalError("trashed conversation not found", http.StatusNotFound, 2002105)
	registerAdditionalError("purge conversation failed", http.StatusInternalServerError, 2002106)
	registerAdditionalError("query conversation trash failed", http.StatusInternalServerError, 2002107)
	registerAdditionalError("empty conversation trash failed", http.StatusInternalServerError, 2002108)
	registerAdditionalError("query archive folder counts failed", http.StatusInternalServerError, 2002109)
	registerAdditionalError("archive folder name already exists", http.StatusConflict, 2002110)
	registerAdditionalError("create archive folder failed", http.StatusInternalServerError, 2002111)
	registerAdditionalError("workflow id already exists", http.StatusConflict, 2002112)
	registerAdditionalError("purge failed", http.StatusInternalServerError, 2002113)
	registerAdditionalError("empty trash failed", http.StatusInternalServerError, 2002114)
	registerAdditionalError("conversation is in trash", http.StatusConflict, 2002115)
	registerAdditionalError("folder name is required", http.StatusBadRequest, 2002116)
	registerAdditionalErrorPattern("folder name must be at most %d characters", "folder name is too long", http.StatusBadRequest, 2002117)
	registerAdditionalError("invalid archive folder id", http.StatusBadRequest, 2002118)
	registerAdditionalError("update archive folder failed", http.StatusInternalServerError, 2002119)
	registerAdditionalError("archive folder is not empty; choose a move target", http.StatusConflict, 2002120)
	registerAdditionalError("archive folder move target must differ from source", http.StatusBadRequest, 2002121)
	registerAdditionalError("delete archive folder failed", http.StatusInternalServerError, 2002122)
	registerAdditionalError("codex tcp bridge token is required", http.StatusServiceUnavailable, 2002284)
	registerAdditionalError("writer download conversion is too large", http.StatusRequestEntityTooLarge, 2002285)
	registerAdditionalError("slot must be source_document, outline_document, flat_draft_document, or draft_document", http.StatusBadRequest, 2002286)
	registerAdditionalError("active", http.StatusNotFound, 2002287)
	registerAdditionalError("slot must be outline_document, flat_draft_document, or draft_document", http.StatusBadRequest, 2002288)
	registerAdditionalError("invalid document", http.StatusBadRequest, 2002289)
	registerAdditionalError("decode attempt result", http.StatusInternalServerError, 2002290)
	registerAdditionalErrorPattern("control.next_step %q is not a reachable choice from %q", "Workflow next step is not reachable", http.StatusInternalServerError, 2002291)
	registerAdditionalErrorPattern("current %s revision is already synchronized", "Conflict", http.StatusConflict, 2000107)
	registerAdditionalErrorPattern("single-cardinality material %q has multiple distinct input bindings", "Internal server error", http.StatusInternalServerError, 2000000)

	// Chat attachment, editable PPTX, and Workflow artifact errors.
	registerAdditionalErrorPattern("resolve turn %q", "Failed to resolve chat turn attachments", http.StatusInternalServerError, 2002123)
	registerAdditionalError("invalid editable pptx bundle manifest", http.StatusBadRequest, 2002124)
	registerAdditionalErrorPattern("editable pptx dependency bundle targets %s/%s, current runtime is %s/%s", "Editable PPTX dependency bundle targets a different platform", http.StatusBadRequest, 2002125)
	registerAdditionalError("editable pptx dependency install is only supported in local/desktop runtime", http.StatusForbidden, 2002126)
	registerAdditionalErrorPattern("editable pptx dependency bundle is not configured for %s/%s", "Editable PPTX dependency bundle is not configured for this platform", http.StatusBadRequest, 2002127)
	registerAdditionalError("extract editable pptx dependency bundle", http.StatusBadRequest, 2002128)
	registerAdditionalError("editable pptx dependency validation failed", http.StatusBadRequest, 2002129)
	registerAdditionalError("editable pptx install completed but chromium was not detected", http.StatusInternalServerError, 2002130)
	registerAdditionalError("lazymind_ppt_export_cli / lazymind_workflows_dir is not set", http.StatusServiceUnavailable, 2002131)
	registerAdditionalError("editable ppt deps node_modules missing", http.StatusBadRequest, 2002132)
	registerAdditionalError("create exporter node_modules link", http.StatusInternalServerError, 2002133)
	registerAdditionalError("mklink /j failed", http.StatusInternalServerError, 2002134)
	registerAdditionalErrorPattern("editable pptx dependency bundle is not supported on %s/%s", "Editable PPTX dependency bundle is not supported on this platform", http.StatusBadRequest, 2002135)
	registerAdditionalError("editable pptx dependency download failed", http.StatusBadGateway, 2002136)
	registerAdditionalError("download editable pptx dependency bundle", http.StatusBadGateway, 2002137)
	registerAdditionalError("editable pptx dependency bundle sha256 is not configured", http.StatusBadRequest, 2002138)
	registerAdditionalError("editable pptx dependency bundle checksum mismatch", http.StatusBadGateway, 2002139)
	registerAdditionalError("unsafe absolute symlink in archive", http.StatusBadRequest, 2002140)
	registerAdditionalError("unsafe symlink target in archive", http.StatusBadRequest, 2002141)
	registerAdditionalError("unsafe archive path", http.StatusBadRequest, 2002142)
	registerAdditionalError("playwright chromium cannot start", http.StatusInternalServerError, 2002143)
	registerAdditionalError("build ppt capabilities request failed", http.StatusInternalServerError, 2002144)
	registerAdditionalError("ppt capabilities upstream unreachable", http.StatusBadGateway, 2002145)
	registerAdditionalError("ppt capabilities upstream error", http.StatusBadGateway, 2002146)
	registerAdditionalError("invalid ppt capabilities response", http.StatusBadGateway, 2002147)
	registerAdditionalError("ppt export upstream unreachable", http.StatusBadGateway, 2002148)
	registerAdditionalError("final ppt action revision is incomplete", http.StatusInternalServerError, 2002149)
	registerAdditionalError("parse workflow slot manifest", http.StatusInternalServerError, 2002150)
	registerAdditionalErrorPattern("artifact slot %q is not declared in workflow revision %s", "Artifact slot is not declared in the Workflow revision", http.StatusUnprocessableEntity, 2002151)
	registerAdditionalError("import files failed", http.StatusInternalServerError, 2002152)
	registerAdditionalErrorPattern("import market files batch %d failed", "import market files batch %d failed", http.StatusInternalServerError, 2002153)
	registerAdditionalError("input_extensions is required", http.StatusInternalServerError, 2002154)
	registerAdditionalErrorAlias("internal server error", "Internal server error", http.StatusInternalServerError, 2000000)
	registerAdditionalErrorPattern("invalid archive entry %q", "invalid archive entry %q", http.StatusInternalServerError, 2002155)
	registerAdditionalError("invalid install payload", http.StatusInternalServerError, 2002156)
	registerAdditionalError("invalid package url", http.StatusInternalServerError, 2002157)
	registerAdditionalError("invalid status", http.StatusBadRequest, 2002158)
	registerAdditionalError("invalid update payload", http.StatusInternalServerError, 2002159)
	registerAdditionalError("invalid update-all payload", http.StatusInternalServerError, 2002160)
	registerAdditionalError("job_id is required", http.StatusBadRequest, 2002161)
	registerAdditionalError("kb service delete failed", http.StatusInternalServerError, 2002162)
	registerAdditionalError("knowledge base has no download package configured", http.StatusBadRequest, 2002163)
	registerAdditionalError("knowledge base has no package url", http.StatusInternalServerError, 2002164)
	registerAdditionalError("knowledge base is not installed", http.StatusNotFound, 2002165)
	registerAdditionalError("knowledge base task is running, retry later", http.StatusConflict, 2002166)
	registerAdditionalError("knowledge base update task is running, retry later", http.StatusConflict, 2002167)
	registerAdditionalErrorPattern("knowledge market catalog contains duplicate id %q", "knowledge market catalog contains duplicate id %q", http.StatusInternalServerError, 2002168)
	registerAdditionalErrorPattern("knowledge market catalog item %q has invalid category %q", "knowledge market catalog item %q has invalid category %q", http.StatusInternalServerError, 2002169)
	registerAdditionalError("knowledge market catalog item requires non-empty id, name and category", http.StatusInternalServerError, 2002170)
	registerAdditionalError("knowledge market catalog yaml path is required", http.StatusInternalServerError, 2002171)
	registerAdditionalError("knowledge market item not found", http.StatusNotFound, 2002172)
	registerAdditionalError("knowledge market task not found", http.StatusNotFound, 2002173)
	registerAdditionalError("lfs object checksum mismatch", http.StatusInternalServerError, 2002174)
	registerAdditionalError("lfs object size mismatch", http.StatusInternalServerError, 2002175)
	registerAdditionalErrorPattern("lfs pointer %s has invalid size", "lfs pointer %s has invalid size", http.StatusInternalServerError, 2002176)
	registerAdditionalErrorPattern("lfs pointer %s has no oid", "lfs pointer %s has no oid", http.StatusInternalServerError, 2002177)
	registerAdditionalErrorPattern("lfs pointer found but host %q is not supported", "lfs pointer found but host %q is not supported", http.StatusInternalServerError, 2002178)
	registerAdditionalErrorPattern("market import canceled before batch %d", "market import canceled before batch %d", http.StatusInternalServerError, 2002179)
	registerAdditionalError("market_item_id and x-user-id are required", http.StatusBadRequest, 2002180)
	registerAdditionalError("materialize source files failed", http.StatusInternalServerError, 2002181)
	registerAdditionalError("nested template expressions are not supported", http.StatusInternalServerError, 2002182)
	registerAdditionalErrorPattern("nested zip extraction exceeded depth %d", "nested zip extraction exceeded depth %d", http.StatusInternalServerError, 2002183)
	registerAdditionalErrorPattern("normalize %s failed", "normalize %s failed", http.StatusInternalServerError, 2002184)
	registerAdditionalError("not a git repository url", http.StatusInternalServerError, 2002185)
	registerAdditionalErrorPattern("open zip %s failed", "open zip %s failed", http.StatusInternalServerError, 2002186)
	registerAdditionalErrorPattern("package %s produced no files", "package %s produced no files", http.StatusInternalServerError, 2002187)
	registerAdditionalError("package contains no files", http.StatusInternalServerError, 2002188)
	registerAdditionalError("query active market jobs failed", http.StatusInternalServerError, 2002189)
	registerAdditionalError("query active market update batch failed", http.StatusInternalServerError, 2002190)
	registerAdditionalError("query active update batch failed", http.StatusInternalServerError, 2002191)
	registerAdditionalError("query dataset failed", http.StatusInternalServerError, 2002192)
	registerAdditionalError("query market install failed", http.StatusInternalServerError, 2002193)
	registerAdditionalErrorPattern("read chinatax parquet %s", "read chinatax parquet %s", http.StatusInternalServerError, 2002194)
	registerAdditionalErrorPattern("read front matter from %s", "read front matter from %s", http.StatusInternalServerError, 2002195)
	registerAdditionalError("read git clone progress failed", http.StatusInternalServerError, 2002196)
	registerAdditionalErrorPattern("read tabular rows from %s", "read tabular rows from %s", http.StatusInternalServerError, 2002197)
	registerAdditionalError("relative_path_template", http.StatusInternalServerError, 2002198)
	registerAdditionalErrorPattern("remove nested zip %s failed", "remove nested zip %s failed", http.StatusInternalServerError, 2002199)
	registerAdditionalErrorPattern("render display name for %s", "render display name for %s", http.StatusInternalServerError, 2002200)
	registerAdditionalErrorPattern("render display name for %s row %d", "render display name for %s row %d", http.StatusInternalServerError, 2002201)
	registerAdditionalErrorPattern("render document template for %s row %d", "render document template for %s row %d", http.StatusInternalServerError, 2002202)
	registerAdditionalErrorPattern("render relative path for %s", "render relative path for %s", http.StatusInternalServerError, 2002203)
	registerAdditionalErrorPattern("render relative path for %s row %d", "render relative path for %s row %d", http.StatusInternalServerError, 2002204)
	registerAdditionalErrorPattern("render tags for %s", "render tags for %s", http.StatusInternalServerError, 2002205)
	registerAdditionalErrorPattern("render tags for %s row %d", "render tags for %s row %d", http.StatusInternalServerError, 2002206)
	registerAdditionalErrorPattern("resolve group for %s", "resolve group for %s", http.StatusInternalServerError, 2002207)
	registerAdditionalErrorPattern("resolve lfs object %s failed", "resolve lfs object %s failed", http.StatusInternalServerError, 2002208)
	registerAdditionalErrorPattern("resolve title for %s", "resolve title for %s", http.StatusInternalServerError, 2002209)
	registerAdditionalError("row_limit must be zero or a positive number", http.StatusInternalServerError, 2002210)
	registerAdditionalError("soft delete documents failed", http.StatusInternalServerError, 2002211)
	registerAdditionalError("source adapter produced no documents", http.StatusInternalServerError, 2002212)
	registerAdditionalErrorPattern("strip front matter from %s", "strip front matter from %s", http.StatusInternalServerError, 2002213)
	registerAdditionalError("submit parse tasks failed", http.StatusInternalServerError, 2002214)
	registerAdditionalError("tabular row limit reached", http.StatusInternalServerError, 2002215)
	registerAdditionalError("tag template", http.StatusInternalServerError, 2002216)
	registerAdditionalError("unclosed template expression", http.StatusInternalServerError, 2002217)
	registerAdditionalError("unclosed template expression in template", http.StatusInternalServerError, 2002218)
	registerAdditionalError("unexpected closing braces in template", http.StatusInternalServerError, 2002219)
	registerAdditionalErrorPattern("unknown source adapter %q", "unknown source adapter %q", http.StatusInternalServerError, 2002220)
	registerAdditionalErrorPattern("unknown template field %q", "unknown template field %q", http.StatusInternalServerError, 2002221)
	registerAdditionalErrorPattern("unsupported package url scheme %q", "unsupported package url scheme %q", http.StatusInternalServerError, 2002222)
	registerAdditionalErrorPattern("unsupported tabular extension %q", "unsupported tabular extension %q", http.StatusInternalServerError, 2002223)
	registerAdditionalErrorPattern("write chinatax document %s", "write chinatax document %s", http.StatusInternalServerError, 2002224)
	registerAdditionalErrorPattern("write download %s failed", "write download %s failed", http.StatusInternalServerError, 2002225)
	registerAdditionalErrorPattern("write tabular document %s", "write tabular document %s", http.StatusInternalServerError, 2002226)
	registerAdditionalError("zip entry is a symlink", http.StatusInternalServerError, 2002227)
	registerAdditionalErrorPattern("%s contains an empty pattern", "%s contains an empty pattern", http.StatusInternalServerError, 2002228)
	registerAdditionalErrorPattern("%s pattern %q is invalid", "%s pattern %q is invalid", http.StatusInternalServerError, 2002229)
	registerAdditionalErrorPattern("adapter %s", "adapter %s", http.StatusInternalServerError, 2002230)
	registerAdditionalError("archive entry escapes destination", http.StatusInternalServerError, 2002231)
	registerAdditionalErrorPattern("cannot parse huggingface repo path %q", "cannot parse huggingface repo path %q", http.StatusInternalServerError, 2002232)
	registerAdditionalErrorPattern("cannot parse modelscope repo path %q", "cannot parse modelscope repo path %q", http.StatusInternalServerError, 2002233)
	registerAdditionalError("check dataset documents failed", http.StatusInternalServerError, 2002234)
	registerAdditionalError("check embedding model failed", http.StatusInternalServerError, 2002235)
	registerAdditionalError("check remote revision failed", http.StatusInternalServerError, 2002236)
	registerAdditionalError("clear old documents failed", http.StatusInternalServerError, 2002237)
	registerAdditionalErrorPattern("copy %s failed", "copy %s failed", http.StatusInternalServerError, 2002238)
	registerAdditionalError("create chinatax generated dir", http.StatusInternalServerError, 2002239)
	registerAdditionalError("create dataset dir failed", http.StatusInternalServerError, 2002240)
	registerAdditionalError("create document/task rows failed", http.StatusInternalServerError, 2002241)
	registerAdditionalError("create generic markdown generated dir", http.StatusInternalServerError, 2002242)
	registerAdditionalError("create generic tabular generated dir", http.StatusInternalServerError, 2002243)
	registerAdditionalErrorPattern("dataset %s does not belong to user %s", "dataset %s does not belong to user %s", http.StatusInternalServerError, 2002244)
	registerAdditionalError("dataset and files are required", http.StatusInternalServerError, 2002245)
	registerAdditionalError("decode install payload", http.StatusInternalServerError, 2002246)
	registerAdditionalError("decode jsonl row", http.StatusInternalServerError, 2002247)
	registerAdditionalError("decode source options", http.StatusInternalServerError, 2002248)
	registerAdditionalError("decode update payload", http.StatusInternalServerError, 2002249)
	registerAdditionalError("decode update-all payload", http.StatusInternalServerError, 2002250)
	registerAdditionalError("delete market install failed", http.StatusInternalServerError, 2002251)
	registerAdditionalError("delete market install/update jobs failed", http.StatusInternalServerError, 2002252)
	registerAdditionalError("display_name and user are required", http.StatusInternalServerError, 2002253)
	registerAdditionalError("display_name_template", http.StatusInternalServerError, 2002254)
	registerAdditionalErrorPattern("doc_mode %q is not supported; only row is currently supported", "doc_mode %q is not supported; only row is currently supported", http.StatusInternalServerError, 2002255)
	registerAdditionalError("document_template is required for doc_mode=row", http.StatusInternalServerError, 2002256)
	registerAdditionalError("download package failed", http.StatusInternalServerError, 2002257)
	registerAdditionalErrorPattern("duplicate generic group name %q", "duplicate generic group name %q", http.StatusInternalServerError, 2002258)
	registerAdditionalError("empty template expression", http.StatusInternalServerError, 2002259)
	registerAdditionalError("enqueue install job failed", http.StatusInternalServerError, 2002260)
	registerAdditionalError("enqueue update job failed", http.StatusInternalServerError, 2002261)
	registerAdditionalError("enqueue update-all job failed", http.StatusInternalServerError, 2002262)
	registerAdditionalErrorPattern("extension %q must look like .ext", "extension %q must look like .ext", http.StatusInternalServerError, 2002263)
	registerAdditionalErrorPattern("extract nested zip %s failed", "extract nested zip %s failed", http.StatusInternalServerError, 2002264)
	registerAdditionalErrorPattern("extract zip entry %s failed", "extract zip entry %s failed", http.StatusInternalServerError, 2002265)
	registerAdditionalErrorPattern("generic group %q display_name_template", "generic group %q display_name_template", http.StatusInternalServerError, 2002266)
	registerAdditionalErrorPattern("generic group %q relative_path_template", "generic group %q relative_path_template", http.StatusInternalServerError, 2002267)
	registerAdditionalErrorPattern("generic group %q requires at least one match pattern", "generic group %q requires at least one match pattern", http.StatusInternalServerError, 2002268)
	registerAdditionalErrorPattern("generic group %q tag template", "generic group %q tag template", http.StatusInternalServerError, 2002269)
	registerAdditionalError("generic group name is required", http.StatusInternalServerError, 2002270)
	registerAdditionalErrorPattern("get %s failed", "get %s failed", http.StatusInternalServerError, 2002271)
	registerAdditionalErrorPattern("git clone %s failed", "git clone %s failed", http.StatusInternalServerError, 2002272)
	registerAdditionalError("git clone start failed", http.StatusInternalServerError, 2002273)
	registerAdditionalError("git clone stderr pipe failed", http.StatusInternalServerError, 2002274)
	registerAdditionalErrorPattern("git ls-remote %s failed", "git ls-remote %s failed", http.StatusInternalServerError, 2002275)
	registerAdditionalErrorPattern("git ls-remote %s returned no commit", "git ls-remote %s returned no commit", http.StatusInternalServerError, 2002276)
	registerAdditionalError("git rev-parse head failed", http.StatusInternalServerError, 2002277)
	registerAdditionalErrorPattern("git rev-parse head returned invalid commit %q", "git rev-parse head returned invalid commit %q", http.StatusInternalServerError, 2002278)
	registerAdditionalErrorPattern("hash %s failed", "hash %s failed", http.StatusInternalServerError, 2002279)
	registerAdditionalError("at least two internal skills are required", http.StatusBadRequest, 2002280)
	registerAdditionalError("zip downloader is not configured", http.StatusInternalServerError, 2002281)
	registerAdditionalErrorPattern("unsupported market skill source type %q", "Unsupported market skill source type", http.StatusBadRequest, 2002282)
	registerAdditionalError("skill package stored path is required", http.StatusBadRequest, 2002283)
	registerAdditionalError("distribution binding is incomplete", http.StatusInternalServerError, 2002295)
	registerAdditionalError("distribution upgrade service is not configured", http.StatusInternalServerError, 2002296)
	registerAdditionalError("latest builtin Skill distribution was not found", http.StatusNotFound, 2002297)
	registerAdditionalError("cannot prepare distribution upgrade while draft overlay exists", http.StatusConflict, 2002298)
	registerAdditionalError("installed Skill distribution baseline is unavailable", http.StatusConflict, 2002299)
	registerAdditionalError("distribution upgrade conflicts require draft review", http.StatusConflict, 2002300)
	registerAdditionalError("distribution upgrade draft is active", http.StatusConflict, 2002301)
	registerAdditionalError("editable content exceeds the 2 mib limit", http.StatusBadRequest, 2002302)
	registerAdditionalError("editable block changed; refresh and retry", http.StatusConflict, 2002303)
	registerAdditionalError("save editable block failed", http.StatusInternalServerError, 2002304)
	registerAdditionalError("failed to invalidate compressed context", http.StatusInternalServerError, 2002307)
	registerAdditionalErrorPattern("artifact slot %q requires content type %q, got %q", "Artifact content type does not match the Workflow slot declaration", http.StatusUnprocessableEntity, 2002308)
	registerAdditionalError("selected evo model is not supported by OpenCode", http.StatusBadRequest, 2002309)
	registerAdditionalError("model free_auto_select_priority must not be negative", http.StatusInternalServerError, 2002312)
	registerAdditionalError("model free_auto_select_base_urls requires a positive free_auto_select_priority", http.StatusInternalServerError, 2002313)
	registerAdditionalError("model free_auto_select_base_urls must not contain an empty URL", http.StatusInternalServerError, 2002314)
	registerAdditionalError("marshal model free_auto_select_base_urls", http.StatusInternalServerError, 2002315)
	registerAdditionalError("selection offsets do not match content", http.StatusBadRequest, 2002316)
	registerAdditionalError("generate endpoint returned invalid editable polish content", http.StatusBadGateway, 2002317)
	registerAdditionalError("base_url must be an api root without a request path", http.StatusBadRequest, 2002319)
	registerAdditionalError("restore model failed", http.StatusInternalServerError, 2002320)
	registerAdditionalError("thinking_depth must be 'low', 'medium', 'high', or 'max'", http.StatusBadRequest, 2002321)
	registerAdditionalError("sidechat cannot change workflow mode", http.StatusConflict, 2002322)
	registerAdditionalError("sidechat cannot enable workflows", http.StatusConflict, 2002323)
	registerAdditionalError("sidechat cannot enable subagents", http.StatusConflict, 2002324)
	registerAdditionalError("sidechat cannot change chat executor", http.StatusConflict, 2002325)
	registerAdditionalError("sidechat requires streaming", http.StatusBadRequest, 2002326)
	registerAdditionalError("sidechat request already accepted; resume the existing response", http.StatusConflict, 2002327)
	registerAdditionalError("sidechat not found", http.StatusNotFound, 2002328)
	registerAdditionalError("failed to claim regenerated history for run", http.StatusInternalServerError, 2002329)
	registerAdditionalError("extend sidechat session failed", http.StatusInternalServerError, 2002330)
	registerAdditionalError("use the sidechat retain operation", http.StatusConflict, 2002331)
	registerAdditionalError("at least one search config field is required", http.StatusBadRequest, 2002332)
	registerAdditionalError("invalid parent conversation", http.StatusBadRequest, 2002333)
	registerAdditionalError("invalid sidechat request", http.StatusBadRequest, 2002334)
	registerAdditionalError("parent conversation not found", http.StatusNotFound, 2002335)
	registerAdditionalError("create sidechat failed", http.StatusInternalServerError, 2002336)
	registerAdditionalError("invalid child conversation", http.StatusBadRequest, 2002337)
	registerAdditionalError("check sidechat status failed", http.StatusInternalServerError, 2002338)
	registerAdditionalError("retain sidechat failed", http.StatusInternalServerError, 2002339)
	registerAdditionalError("discard sidechat failed", http.StatusInternalServerError, 2002340)
	registerAdditionalErrorPattern("at most %d %s are allowed", "Too many search configuration values", http.StatusBadRequest, 2002341)
	registerAdditionalErrorPattern("%s value is too long", "Search configuration value is too long", http.StatusBadRequest, 2002342)
	registerAdditionalError("sidechat nesting limit reached", http.StatusConflict, 2002343)
	registerAdditionalError("sidechat source message not found", http.StatusBadRequest, 2002344)
	registerAdditionalError("sidechat source message is still generating", http.StatusConflict, 2002345)
	registerAdditionalError("sidechat has no completed user message to retain", http.StatusConflict, 2002346)
	registerAdditionalError("child conversation must follow its parent group state", http.StatusConflict, 2002347)
	registerAdditionalError("sidechat already has a request in progress", http.StatusConflict, 2002348)
	registerAdditionalError("sidechat request was already accepted", http.StatusConflict, 2002349)
	registerAdditionalError("sidechat knowledge bases are inherited from the parent conversation", http.StatusConflict, 2002350)
	registerAdditionalError("invalid sidechat client_request_id", http.StatusBadRequest, 2002351)
	registerAdditionalError("invalid trailing json", http.StatusBadRequest, 2002352)
	registerAdditionalError("invalid sidechat source", http.StatusBadRequest, 2002353)
	registerAdditionalError("invalid thinking depth", http.StatusBadRequest, 2002354)
	registerAdditionalError("sidechat source attachment is no longer available", http.StatusConflict, 2002355)
	registerAdditionalError("sidechat source attachment access denied", http.StatusForbidden, 2002356)
	registerAdditionalError("chat source attachment store is not configured", http.StatusInternalServerError, 2002357)
	registerAdditionalError("query chat source upload", http.StatusInternalServerError, 2002358)
	registerAdditionalError("query chat source upload session", http.StatusInternalServerError, 2002359)
	registerAdditionalError("query chat source datasets", http.StatusInternalServerError, 2002360)
	registerAdditionalError("invalid external Agent attachment", http.StatusBadRequest, 2002367)
	registerAdditionalErrorAlias("invalid external Agent attachment content", "invalid external Agent attachment", http.StatusBadRequest, 2002367)
	registerAdditionalError("create external Agent attachment reference", http.StatusInternalServerError, 2002368)
	registerAdditionalError("external Agent attachment event conflicts with existing content", http.StatusConflict, 2002369)
	registerAdditionalErrorAlias("skill_id required", "missing skill_id", http.StatusBadRequest, 2000854)
	registerAdditionalError("invalid history selection", http.StatusBadRequest, 2002370)
	registerAdditionalError("failed to start history run", http.StatusConflict, 2002371)
	registerAdditionalError("editable block unavailable or changed; refresh and retry", http.StatusConflict, 2002372)
	registerAdditionalError("inspect chat source attachment", http.StatusInternalServerError, 2002373)
	registerAdditionalError("text is required", http.StatusBadRequest, 2002374)
	registerAdditionalError("text exceeds 5000 characters", http.StatusBadRequest, 2002375)
	registerAdditionalError("translation service is not configured", http.StatusPreconditionFailed, 2002376)
	registerAdditionalError("unsupported translation provider", http.StatusBadRequest, 2002377)
	registerAdditionalError("invalid translation credentials", http.StatusPreconditionFailed, 2002378)
	registerAdditionalError("SecretId and SecretKey are required", http.StatusPreconditionFailed, 2002379)
	registerAdditionalError("invalid Tencent translation endpoint", http.StatusBadRequest, 2002380)
	registerAdditionalErrorPattern("Tencent translation request failed: %w", "Tencent translation request failed", http.StatusBadGateway, 2002381)
	registerAdditionalErrorAlias("Tencent translation request failed", "Tencent translation request failed", http.StatusBadGateway, 2002381)
	registerAdditionalErrorPattern("Tencent translation returned HTTP %d", "Tencent translation returned an invalid response", http.StatusBadGateway, 2002382)
	registerAdditionalErrorPattern("Tencent translation failed: %s", "Tencent translation failed", http.StatusBadGateway, 2002383)
	registerAdditionalErrorAlias("Tencent translation failed", "Tencent translation failed", http.StatusBadGateway, 2002383)
	registerAdditionalError("list document vocabulary failed", http.StatusInternalServerError, 2002384)
	registerAdditionalError("invalid AnkiConnect endpoint", http.StatusBadRequest, 2002385)
	registerAdditionalError("AnkiConnect endpoint must use loopback", http.StatusBadRequest, 2002386)
	registerAdditionalErrorPattern("AnkiConnect unavailable: %w", "AnkiConnect unavailable", http.StatusBadGateway, 2002387)
	registerAdditionalErrorAlias("AnkiConnect unavailable", "AnkiConnect unavailable", http.StatusBadGateway, 2002387)
	registerAdditionalErrorPattern("AnkiConnect returned HTTP %d", "AnkiConnect returned an invalid response", http.StatusBadGateway, 2002388)
	registerAdditionalError("AnkiConnect returned invalid JSON", http.StatusBadGateway, 2002389)
	registerAdditionalErrorPattern("AnkiConnect: %v", "AnkiConnect request failed", http.StatusBadGateway, 2002390)
	registerAdditionalErrorAlias("AnkiConnect", "AnkiConnect request failed", http.StatusBadGateway, 2002390)
	registerAdditionalError("AnkiConnect did not accept the answer", http.StatusConflict, 2002391)
	registerAdditionalError("no dictionary sources configured", http.StatusPreconditionFailed, 2002392)
	registerAdditionalError("local vocabulary provider is only available in desktop runtime", http.StatusPreconditionFailed, 2002393)
	registerAdditionalError("vocabulary feature is disabled", http.StatusNotFound, 2002406)
	registerAdditionalError("wordbook name is required", http.StatusBadRequest, 2002394)
	registerAdditionalError("sentence is required", http.StatusBadRequest, 2002395)
	registerAdditionalError("invalid vocabulary provider", http.StatusBadRequest, 2002396)
	registerAdditionalError("invalid rating", http.StatusBadRequest, 2002397)
	registerAdditionalError("previewed_at is required", http.StatusBadRequest, 2002398)
	registerAdditionalError("review card changed", http.StatusConflict, 2002399)
	registerAdditionalError("fsrs weights must contain 19 numeric values for go-fsrs/v3", http.StatusBadRequest, 2002400)
	registerAdditionalError("desired retention must be between 0.70 and 0.99", http.StatusBadRequest, 2002401)
	registerAdditionalError("maximum interval must be between 1 and 36500 days", http.StatusBadRequest, 2002402)
	registerAdditionalError("Anki deck name is required", http.StatusBadRequest, 2002403)
	registerAdditionalErrorPattern("unsupported queued Anki operation: %s", "Unsupported queued Anki operation", http.StatusBadRequest, 2002404)
	registerAdditionalErrorAlias("unsupported queued Anki operation", "Unsupported queued Anki operation", http.StatusBadRequest, 2002404)
	registerAdditionalErrorPattern("AnkiConnect queue flush failed: %s", "AnkiConnect queue flush failed", http.StatusBadGateway, 2002405)
	registerAdditionalErrorAlias("AnkiConnect queue flush failed", "AnkiConnect queue flush failed", http.StatusBadGateway, 2002405)
	registerAdditionalError("update model failed", http.StatusInternalServerError, 2002626)
	registerAdditionalError("max_input_tokens is required", http.StatusBadRequest, 2002627)
	registerAdditionalError("catalog model max_input_tokens cannot be updated", http.StatusBadRequest, 2002628)
	registerAdditionalError("decode api key failed", http.StatusInternalServerError, 2002629)
	registerAdditionalError("group base_url host is not allowed", http.StatusBadRequest, 2002630)
	registerAdditionalError("build remote models request failed", http.StatusInternalServerError, 2002631)
	registerAdditionalError("list remote models failed", http.StatusBadGateway, 2002632)
	registerAdditionalError("read context windows", http.StatusInternalServerError, 2002633)
	registerAdditionalError("parse context windows", http.StatusInternalServerError, 2002634)
	registerAdditionalError("context windows entry is missing a model type", http.StatusInternalServerError, 2002635)
	registerAdditionalErrorPattern("context windows %s entry is missing a model name", "context windows entry is missing a model name", http.StatusInternalServerError, 2002636)
	registerAdditionalErrorPattern("context windows %s %q", "invalid context windows entry", http.StatusInternalServerError, 2002637)
	registerAdditionalErrorPattern("context windows has conflicting %s values for %q", "context windows has conflicting values", http.StatusInternalServerError, 2002638)
	registerAdditionalError("invalid group base_url", http.StatusBadRequest, 2002639)
	registerAdditionalError("group base_url must use http or https", http.StatusBadRequest, 2002640)
	registerAdditionalError("group base_url must not include credentials", http.StatusBadRequest, 2002641)
	registerAdditionalError("artifact is in use by a running workflow attempt", http.StatusConflict, 2002647)
	registerAdditionalError("skill conversion preflight failed", http.StatusInternalServerError, 2002800)
	registerAdditionalError("cancel generation failed", http.StatusInternalServerError, 2002801)
	registerAdditionalError("workflow draft generation canceled", http.StatusConflict, 2002802)
	registerAdditionalError("repair returned empty workflow_yaml", http.StatusBadGateway, 2002803)
	registerAdditionalError("repair returned empty scenario.md", http.StatusBadGateway, 2002804)
	registerAdditionalError("save generated script audit", http.StatusInternalServerError, 2002805)
	registerAdditionalError("save repaired script audit", http.StatusInternalServerError, 2002806)
	registerAdditionalError("sync workflow capabilities failed", http.StatusInternalServerError, 2002807)
	registerAdditionalError("finalize draft failed", http.StatusInternalServerError, 2002808)
	registerAdditionalError("ARTIFACT_NOT_FOUND", http.StatusNotFound, 2002822)
	registerAdditionalError("ARTIFACT_REVISION_CONFLICT", http.StatusConflict, 2002823)
	registerAdditionalError("ARTIFACT_IDEMPOTENCY_CONFLICT", http.StatusConflict, 2002824)
	registerAdditionalError("ARTIFACT_BLOB_HASH_MISMATCH", http.StatusBadRequest, 2002825)
	registerAdditionalError("ARTIFACT_ACCESS_DENIED", http.StatusForbidden, 2002826)
	registerAdditionalError("ARTIFACT_QUOTA_EXCEEDED", http.StatusTooManyRequests, 2002827)
	registerAdditionalError("ARTIFACT_V2_DISABLED", http.StatusNotFound, 2002828)
	registerAdditionalError("query conversation uploads failed", http.StatusInternalServerError, 2002829)
	registerAdditionalError("audit report must not include paths or urls", http.StatusInternalServerError, 2002830)
	registerAdditionalError("artifact revision payload is immutable", http.StatusConflict, 2002831)
	registerAdditionalError("ARTIFACT_SHADOW_TOO_LARGE", http.StatusRequestEntityTooLarge, 2002832)
	registerAdditionalError("file artifact path is missing", http.StatusBadRequest, 2002833)
	registerAdditionalError("file artifact path is not a regular file", http.StatusBadRequest, 2002834)
	registerAdditionalError("query published artifacts failed", http.StatusInternalServerError, 2002835)
	registerAdditionalError("query artifact deliveries failed", http.StatusInternalServerError, 2002836)
	registerAdditionalErrorAlias("revision_id is required", "revision_id required", http.StatusBadRequest, 2001509)
	registerAdditionalError("too many dictionary entries", http.StatusBadRequest, 2003000)
	registerAdditionalError("unsupported dictionary provider", http.StatusBadRequest, 2003001)
	registerAdditionalError("dictionary provenance and valid payload_json are required", http.StatusBadRequest, 2003002)
	registerAdditionalError("dataset_id, document_id, capability_keys and items are required", http.StatusBadRequest, 2003003)
	registerAdditionalError("preanalysis capability is not enabled for knowledge base", http.StatusBadRequest, 2003004)
	registerAdditionalError("preanalysis task is already running", http.StatusConflict, 2003005)
	registerAdditionalError("invalid stored preanalysis request", http.StatusInternalServerError, 2003006)
	registerAdditionalError("dictionary entry payload is invalid", http.StatusInternalServerError, 2003007)
	registerAdditionalError("model did not return json", http.StatusBadGateway, 2003008)
	registerAdditionalError("unsupported learning capability", http.StatusBadRequest, 2003009)
	registerAdditionalError("selection is incompatible with capability", http.StatusBadRequest, 2003010)
	registerAdditionalError("resolved content misses required fields", http.StatusBadGateway, 2003011)
	registerAdditionalError("learning collection capability mismatch", http.StatusBadRequest, 2003012)
	registerAdditionalError("model returned invalid question schema", http.StatusBadGateway, 2003013)
	registerAdditionalError("learning collection has no question types", http.StatusBadRequest, 2003014)
	registerAdditionalError("learning collection is empty", http.StatusBadRequest, 2003015)
	registerAdditionalError("no cards are due", http.StatusConflict, 2003016)
	registerAdditionalError("rating is required for self-assessed question", http.StatusBadRequest, 2003017)
	registerAdditionalError("learning feature requires the desktop local backend", http.StatusServiceUnavailable, 2003018)
	registerAdditionalError("knowledge base not found or not writable", http.StatusNotFound, 2003019)
	registerAdditionalError("profile name is required", http.StatusBadRequest, 2003020)
	registerAdditionalError("capability profile not found", http.StatusNotFound, 2003021)
	registerAdditionalError("capability profile is invalid", http.StatusInternalServerError, 2003022)
	registerAdditionalError("at least one capability is required", http.StatusBadRequest, 2003023)
	registerAdditionalError("unsupported capability version", http.StatusBadRequest, 2003024)
	registerAdditionalError("duplicate learning capability", http.StatusBadRequest, 2003025)
	registerAdditionalError("invalid preset scope", http.StatusBadRequest, 2003026)
	registerAdditionalError("scope_id is required", http.StatusBadRequest, 2003027)
	registerAdditionalError("question type is not supported by capability", http.StatusBadRequest, 2003028)
	registerAdditionalError("book name is required", http.StatusBadRequest, 2003029)
	registerAdditionalError("question type is not supported by learning capability", http.StatusBadRequest, 2003030)
	registerAdditionalError("learning capability cannot be changed", http.StatusConflict, 2003031)
	registerAdditionalError("target wordbook capability does not match", http.StatusBadRequest, 2003032)
	registerAdditionalError("word content is incompatible with selected learning collection", http.StatusBadRequest, 2003033)
	registerAdditionalError("invalid question type registration", http.StatusInternalServerError, 2003034)
	registerAdditionalError("duplicate question type registration", http.StatusInternalServerError, 2003035)
	registerAdditionalError("invalid capability registration", http.StatusInternalServerError, 2003036)
	registerAdditionalError("duplicate capability registration", http.StatusInternalServerError, 2003037)
	registerAdditionalErrorPattern("invalid schema field registration for %s", "invalid schema field registration", http.StatusInternalServerError, 2003038)
	registerAdditionalErrorPattern("capability %s references unknown provider %s", "capability references unknown provider", http.StatusInternalServerError, 2003039)
	registerAdditionalErrorPattern("capability %s references unknown question type %s", "capability references unknown question type", http.StatusInternalServerError, 2003040)
	registerAdditionalErrorPattern("capability %s has invalid default question type %s", "capability has invalid default question type", http.StatusInternalServerError, 2003041)
	registerAdditionalErrorPattern("capability %s has invalid cache policy", "capability has invalid cache policy", http.StatusInternalServerError, 2003042)
	registerAdditionalError("model returned invalid preanalysis schema", http.StatusBadGateway, 2003043)
	registerAdditionalError("dictionary import metadata is required", http.StatusBadRequest, 2003044)
	registerAdditionalError("preset is not a draft of this task", http.StatusBadRequest, 2003045)
	registerAdditionalError("content is not a draft of this task", http.StatusBadRequest, 2003046)
	registerAdditionalErrorPattern("capability %s has no recipe for question type %s", "learning capability has no registered card recipe", http.StatusInternalServerError, 2003047)
	registerAdditionalError("preanalysis task is not ready to publish", http.StatusConflict, 2003048)
	registerAdditionalError("document revision changed before preanalysis publish", http.StatusConflict, 2003049)
	registerAdditionalError("preanalysis preset failed schema validation", http.StatusBadRequest, 2003050)
	registerAdditionalError("preanalysis content failed schema validation", http.StatusBadRequest, 2003051)
	registerAdditionalError("question prompt is required", http.StatusBadRequest, 2003052)
	registerAdditionalError("question grading is required", http.StatusBadRequest, 2003053)
	registerAdditionalError("question answer is required", http.StatusBadRequest, 2003054)
	registerAdditionalError("question options must be unique", http.StatusBadRequest, 2003055)
	registerAdditionalError("question answer must be one of the options", http.StatusBadRequest, 2003056)
	registerAdditionalError("idempotency key belongs to another answer", http.StatusConflict, 2003057)
	registerAdditionalError("question has already been answered", http.StatusConflict, 2003058)
	registerAdditionalError("selection exceeds capability length limit", http.StatusBadRequest, 2003059)
	registerAdditionalErrorPattern("unsupported capability setting: %s", "unsupported capability setting", http.StatusBadRequest, 2003060)
	registerAdditionalError("unsupported capability setting", http.StatusBadRequest, 2003060)
	registerAdditionalError("cache scope is not allowed for capability", http.StatusBadRequest, 2003061)
	registerAdditionalError("invalid maximum selection length", http.StatusBadRequest, 2003062)
	registerAdditionalError("learning capability is not enabled for knowledge base", http.StatusForbidden, 2003063)
	registerAdditionalError("knowledge base capability settings are invalid", http.StatusBadRequest, 2003064)
	registerAdditionalError("content ids are required", http.StatusBadRequest, 2003065)
	registerAdditionalError("dictionary checksum must be sha-256", http.StatusBadRequest, 2003066)
	registerAdditionalError("dictionary import version metadata conflicts with existing import", http.StatusConflict, 2003067)
	registerAdditionalError("review session is not active", http.StatusConflict, 2003068)
	registerAdditionalError("content is incompatible with the selected learning collection", http.StatusBadRequest, 2003069)
	registerAdditionalError("document chunk generation canceled", http.StatusRequestTimeout, 2003070)
	registerAdditionalError("document chunks are still being generated; please retry shortly", http.StatusConflict, 2003071)
	registerAdditionalErrorPattern("provided content misses required fields: %s", "provided content misses required fields", http.StatusBadRequest, 2003072)
	registerAdditionalError("provided content misses required fields", http.StatusBadRequest, 2003072)
	registerAdditionalError("dataset_id and document_id are required", http.StatusBadRequest, 2003073)
	registerAdditionalError("analysis_direction must not exceed 1000 characters", http.StatusBadRequest, 2003074)
	registerAdditionalErrorPattern("model field %s must be an array of strings", "model field must be an array of strings", http.StatusBadGateway, 2003075)
	registerAdditionalErrorPattern("model field %s must be a string", "model field must be a string", http.StatusBadGateway, 2003076)
	registerAdditionalErrorPattern("model response misses generated fields: %s", "model response misses generated fields", http.StatusBadGateway, 2003077)
	registerAdditionalError("model response misses generated fields", http.StatusBadGateway, 2003077)
	registerAdditionalErrorPattern("invalid %s", "invalid learning capability setting", http.StatusBadRequest, 2003078)
	registerAdditionalError("invalid capability output language", http.StatusBadRequest, 2003079)
	registerAdditionalError("missing user id", http.StatusBadRequest, 2002900)
	registerAdditionalError("list invocation records failed", http.StatusInternalServerError, 2002901)
	registerAdditionalError("unsupported external Agent", http.StatusBadRequest, 2002902)
	registerAdditionalError("invalid capability grant", http.StatusBadRequest, 2002903)
	registerAdditionalError("capability is unavailable; verify and enable its connection first", http.StatusPreconditionFailed, 2002904)
	registerAdditionalError("model context protocol tool is not enabled", http.StatusPreconditionFailed, 2002905)
	registerAdditionalErrorPattern("decode model context protocol credentials: %w", "Stored tool credentials could not be loaded", http.StatusPreconditionFailed, 2002906)
	registerAdditionalErrorAlias("decode model context protocol credentials", "Stored tool credentials could not be loaded", http.StatusPreconditionFailed, 2002906)
	registerAdditionalErrorPattern("model context protocol service connection failed: %w", "Tool service connection failed", http.StatusBadGateway, 2002907)
	registerAdditionalErrorAlias("model context protocol service connection failed", "Tool service connection failed", http.StatusBadGateway, 2002907)
	registerAdditionalErrorPattern("model context protocol tool execution failed: %w", "Tool execution failed", http.StatusBadGateway, 2002908)
	registerAdditionalErrorAlias("model context protocol tool execution failed", "Tool execution failed", http.StatusBadGateway, 2002908)
	registerAdditionalError("built-in tool is not externally callable", http.StatusPreconditionFailed, 2002909)
	registerAdditionalError("encode built-in tool request", http.StatusInternalServerError, 2002910)
	registerAdditionalError("prepare built-in tool request", http.StatusInternalServerError, 2002911)
	registerAdditionalError("built-in tool service is unreachable", http.StatusBadGateway, 2002912)
	registerAdditionalError("built-in tool result could not be read or exceeded 2 MiB", http.StatusBadGateway, 2002913)
	registerAdditionalErrorPattern("built-in tool request failed (%d)", "Built-in tool request failed", http.StatusBadGateway, 2002914)
	registerAdditionalError("built-in tool returned an invalid result", http.StatusBadGateway, 2002915)
	registerAdditionalError("invalid built-in tool catalog", http.StatusBadGateway, 2002916)
	registerAdditionalError("cannot check tool configuration", http.StatusInternalServerError, 2002917)
	registerAdditionalError("cannot load tool configuration", http.StatusInternalServerError, 2002918)

	// Writer document editing and publication errors.
	registerAdditionalError("full_content required for selections", http.StatusBadRequest, 2003080)
	registerAdditionalError("selection_ranges required with full_content", http.StatusBadRequest, 2003081)
	registerAdditionalError("bound provider required", http.StatusConflict, 2003082)
	registerAdditionalError("writer document provider selection required", http.StatusBadRequest, 2003083)
	registerAdditionalError("base_draft_version required", http.StatusBadRequest, 2003084)
	registerAdditionalError("draft version conflict; refresh and retry", http.StatusConflict, 2003085)
	registerAdditionalError("base_revision required", http.StatusBadRequest, 2003086)
	registerAdditionalError("provider sync succeeded but local artifact changed", http.StatusConflict, 2003087)
	registerAdditionalError("artifact draft version lookup failed", http.StatusInternalServerError, 2003088)
	registerAdditionalError("slot revision lookup failed", http.StatusInternalServerError, 2003089)
	registerAdditionalError("LaTeX conversion only supports Markdown source content", http.StatusUnprocessableEntity, 2003090)
	registerAdditionalError("incomplete document inspection", http.StatusBadGateway, 2003091)
	registerAdditionalError("generate endpoint returned invalid editable polish results", http.StatusBadGateway, 2003092)
	registerAdditionalError("provider is required for document conversion", http.StatusBadRequest, 2003093)
	registerAdditionalError("document content is required for conversion", http.StatusBadRequest, 2003094)
	registerAdditionalError("artifact file exceeds limit", http.StatusRequestEntityTooLarge, 2003095)
	registerAdditionalError("artifact file is outside storage", http.StatusForbidden, 2003096)
	registerAdditionalError("multiple or invalid JSON values", http.StatusBadRequest, 2003097)
	registerAdditionalError("snapshot must be a string or IR object", http.StatusBadRequest, 2003098)
	registerAdditionalError("mixed rewrite input", http.StatusBadRequest, 2003099)
	registerAdditionalErrorAlias("revision required", "base_revision required", http.StatusBadRequest, 2003086)
	registerAdditionalErrorAlias("draft version required", "base_draft_version required", http.StatusBadRequest, 2003084)
	registerAdditionalErrorAlias("draft version conflict", "draft version conflict; refresh and retry", http.StatusConflict, 2003085)
	registerAdditionalError("summary model returned empty content", http.StatusBadGateway, 2003115)
	registerAdditionalError("summary model returned the summary instruction instead of a summary", http.StatusBadGateway, 2003114)
	registerAdditionalError("result version changed", http.StatusConflict, 2003100)
	registerAdditionalError("release market task idempotency keys failed", http.StatusInternalServerError, 2003101)
	registerAdditionalError("workflow unavailable", http.StatusServiceUnavailable, 2002919)
	registerAdditionalError("use the authenticated workflow page to change approval preferences", http.StatusForbidden, 2002924)
	registerAdditionalError("artifact file is outside LazyMind storage", http.StatusBadRequest, 2002921)
	registerAdditionalError("artifact must be a regular file of at most 20 MiB", http.StatusBadRequest, 2002922)
	registerAdditionalError("artifact exceeds 20 MiB", http.StatusRequestEntityTooLarge, 2002923)
}

func registerAdditionalError(message string, status, code int) {
	if _, exists := errorCatalog[message]; exists {
		panic("duplicate Core error catalog message: " + message)
	}
	errorCatalog[message] = NewAppError(status, code, message)
}

func registerAdditionalErrorAlias(alias, message string, status, code int) {
	if _, exists := errorCatalog[alias]; exists {
		panic("duplicate Core error catalog alias: " + alias)
	}
	errorCatalog[alias] = NewAppError(status, code, message)
}

func registerAdditionalErrorPattern(template, message string, status, code int) {
	normalizedTemplate := normalizeErrorKey(template)
	for _, pattern := range errorPatterns {
		if pattern.template == normalizedTemplate {
			panic("duplicate Core error catalog pattern: " + template)
		}
	}
	errorPatterns = append(errorPatterns, errorPattern{
		template: normalizedTemplate,
		matcher:  compileErrorPattern(normalizedTemplate),
		appErr:   NewAppError(status, code, message),
	})
}

func compileErrorPattern(template string) *regexp.Regexp {
	var pattern strings.Builder
	pattern.WriteString("^")
	for index := 0; index < len(template); {
		percent := strings.IndexByte(template[index:], '%')
		if percent < 0 {
			pattern.WriteString(regexp.QuoteMeta(template[index:]))
			break
		}
		percent += index
		pattern.WriteString(regexp.QuoteMeta(template[index:percent]))
		if percent+1 < len(template) && template[percent+1] == '%' {
			pattern.WriteString("%")
			index = percent + 2
			continue
		}
		verb := percent + 1
		for verb < len(template) && !unicode.IsLetter(rune(template[verb])) {
			verb++
		}
		if verb >= len(template) {
			pattern.WriteString("%")
			index = percent + 1
			continue
		}
		pattern.WriteString(".+?")
		index = verb + 1
	}
	pattern.WriteString("$")
	return regexp.MustCompile(pattern.String())
}
