// Stable errors introduced by the optional LazyMind Cloud, provider bridge,
// and cloud resource integration. Public handlers preserve their HTTP status;
// these aliases prevent internal implementation details from becoming the
// user-facing message when no more specific catalog entry applies.

package common

import "net/http"

func init() {
	registerAdditionalErrorAlias("expected an http service url", "Expected an HTTP service URL", http.StatusInternalServerError, 2003102)

	for _, source := range []string{
		"binary blob storage key is missing",
		"blob store is not configured",
		"cli_integrity_mismatch",
		"cli_not_installed",
		"cli_output_invalid",
		"cli_timeout",
		"cli_unavailable",
		"cli_version_unsupported",
		"cloud adoption candidate disappeared",
		"cloud login returned an incomplete token pair",
		"cloud model bootstrap is in backoff",
		"cloud model bootstrap refresh is already in flight",
		"cloud model catalog unavailable",
		"cloud model unavailable",
		"cloud models cannot be shared",
		"cloud refresh returned an incomplete token pair",
		"cloud refresh token is empty",
		"cloud refresh token size is invalid",
		"cloud resource binding is incomplete",
		"cloud resource binding type must be skill or workflow",
		"cloud resource cannot be downloaded in its current local state",
		"cloud resource content hash mismatch",
		"cloud resource content size mismatch",
		"cloud resource file exceeds limits",
		"cloud resource metadata is incomplete",
		"cloud resource package exceeds the content limit",
		"cloud resource package is empty",
		"cloud resource request is incomplete",
		"cloud resource type must be skill or workflow",
		"cloud resource upload is not configured",
		"cloud resource upload request is incomplete",
		"cloud resource upload returned an invalid result",
		"cloud resource zip contains a non-regular file",
		"cloud resource zip contains too many files",
		"cloud resource zip content exceeds the limit",
		"cloud resource zip exceeds the archive limit",
		"cloud resource zip executable is outside scripts",
		"cloud resource zip file exceeds the limit",
		"cloud resource zip file size is invalid",
		"cloud skill export request is incomplete",
		"cloud skill import request is incomplete",
		"cloud upload succeeded but local binding failed",
		"cloud workflow already exists locally",
		"cloud workflow export request is incomplete",
		"cloud workflow import request is incomplete",
		"cloud workflow package failed local compilation",
		"cloud workflow package requires workflow.yaml id",
		"cloud_reauth_required",
		"cloud_unavailable",
		"complete cloud upload",
		"create credential vault aead",
		"create credential vault cipher",
		"credential backup could not be disabled",
		"credential backup could not be enabled",
		"credential manifest trust key is not ed25519",
		"credential manifest trust, payload and signature files must all be configured",
		"credential restore conflicts with local credentials",
		"credential restore is temporarily unavailable",
		"credential restore operation was not found",
		"credential restore request is invalid",
		"credential restore request was rejected",
		"credential restore requires a local user",
		"credential restore response contains trailing data",
		"credential vault contract is invalid",
		"credential vault local key was not found",
		"credential vault local state conflicts with cloud",
		"credential vault response omitted a strong etag",
		"decode credential vault key manifest",
		"decode lazymind cloud account",
		"decode lazymind cloud account token plan",
		"decode lazymind cloud credential manifest",
		"decode lazymind cloud credential record",
		"decode lazymind cloud credential record page",
		"decode lazymind cloud credential restore",
		"decode lazymind cloud credential restore operation",
		"decode lazymind cloud credential vault",
		"decode lazymind cloud credential vault member",
		"decode lazymind cloud desktop token response",
		"decode lazymind cloud download authorization",
		"decode lazymind cloud knowledge response",
		"decode lazymind cloud provider bootstrap",
		"decode lazymind cloud provider connection response",
		"decode lazymind cloud refresh response",
		"decode lazymind cloud resource",
		"decode lazymind cloud resource operation",
		"decode lazymind cloud resource page",
		"decode lazymind cloud upload completion",
		"decrypt credential vault payload",
		"delete cloud refresh token from credential manager",
		"delete cloud refresh token from keychain",
		"encode credential vault aad",
		"encode credential vault record signature input",
		"executable file is outside scripts",
		"expired feishu cli sidecar signature",
		"generate credential vault nonce",
		"import cloud skill",
		"import cloud workflow",
		"imported skill content does not match the cloud resource",
		"imported workflow content does not match the cloud resource",
		"invalid auth_connection_id",
		"invalid credential restore operation id",
		"invalid credential restore request",
		"invalid credential vault etag",
		"invalid credential vault member registration",
		"invalid credential vault record",
		"invalid credential vault record query",
		"invalid feishu cli sidecar signature",
		"invalid lazymind cloud base url",
		"invalid lazymind cloud desktop authorization request",
		"invalid lazymind cloud desktop code exchange",
		"invalid lazymind cloud locale",
		"invalid local provider connection configuration",
		"invalid model source",
		"invalid operation_id",
		"invalid provider access token failure report",
		"invalid provider access token lease request",
		"invalid provider connection bridge configuration",
		"invalid provider connection session id",
		"invalid provider token bridge request",
		"invalid provider token failure report",
		"invalid resource page query",
		"invalid resource_id",
		"invalid signed object request",
		"invalid signed upload request",
		"invalid upload part numbers",
		"invalid upload part request",
		"invalid upload_id",
		"lazymind cloud access token has no valid expiry",
		"lazymind cloud access token is not a jwt",
		"lazymind cloud access token is required",
		"lazymind cloud access token payload is invalid",
		"lazymind cloud authorization path is invalid",
		"lazymind cloud base url must be an origin",
		"lazymind cloud base url must use https",
		"lazymind cloud browser login could not start",
		"lazymind cloud callback listener is invalid",
		"lazymind cloud did not initialize the resource upload",
		"lazymind cloud download authorization omitted the signed request",
		"lazymind cloud download preparation timed out",
		"lazymind cloud health check redirected outside its origin",
		"lazymind cloud health response is too large",
		"lazymind cloud is not configured",
		"lazymind cloud knowledge request failed",
		"lazymind cloud knowledge response is invalid",
		"lazymind cloud login dependencies are incomplete",
		"lazymind cloud login locale is invalid",
		"lazymind cloud login origin is invalid",
		"lazymind cloud refresh token is required",
		"lazymind cloud resource listing exceeded the page limit",
		"lazymind cloud resource page exceeds the item limit",
		"lazymind cloud resource response omitted etag",
		"lazymind cloud returned an incomplete desktop token pair",
		"lazymind cloud returned an incomplete token pair",
		"lazymind cloud returned an invalid account",
		"lazymind cloud returned an invalid account token plan",
		"lazymind cloud returned an invalid authorization transaction",
		"lazymind cloud returned an invalid catalog revision",
		"lazymind cloud returned an invalid credential manifest",
		"lazymind cloud returned an invalid credential record",
		"lazymind cloud returned an invalid credential record page",
		"lazymind cloud returned an invalid credential record summary",
		"lazymind cloud returned an invalid credential restore operation",
		"lazymind cloud returned an invalid credential vault",
		"lazymind cloud returned an invalid credential vault member",
		"lazymind cloud returned an invalid inactive token plan",
		"lazymind cloud returned an invalid preparing response",
		"lazymind cloud returned an invalid private resource",
		"lazymind cloud returned an invalid provider access token lease",
		"lazymind cloud returned an invalid provider bootstrap",
		"lazymind cloud returned an invalid provider connection",
		"lazymind cloud returned an invalid provider connection session",
		"lazymind cloud returned an invalid provider refresh time",
		"lazymind cloud returned an invalid public model",
		"lazymind cloud returned an invalid resource operation",
		"lazymind cloud returned an invalid resource timestamp",
		"lazymind cloud returned an invalid signed download request",
		"lazymind cloud returned an invalid token plan quota",
		"lazymind cloud returned an invalid token plan refresh time",
		"lazymind cloud returned an unknown download status",
		"lazymind cloud returned an unknown upload status",
		"lazymind cloud returned an unsupported upload mode",
		"lazymind cloud returned duplicate credential records",
		"lazymind cloud returned duplicate token plan quotas",
		"lazymind cloud returned duplicate token plan usage",
		"lazymind cloud returned invalid token plan usage",
		"lazymind cloud returned invalid upload expiry",
		"lazymind cloud returned invalid upload part authorization",
		"lazymind cloud returned invalid upload part authorizations",
		"lazymind cloud returned invalid upload state",
		"lazymind cloud returned too many provider connections",
		"lazymind cloud upload result does not match the local package",
		"lazymind cloud upload verification timed out",
		"lazymind cloud usage request failed",
		"local cloud resource package is inconsistent",
		"local connection registry rejected the request",
		"local resource id is required",
		"macos keychain requires cgo",
		"managed provider token requires core bridge",
		"multipart upload omitted part_size",
		"multipart upload part count is invalid",
		"multipart upload response omitted etag",
		"object download is not configured",
		"object key is outside the store",
		"profile_not_found",
		"profile_owner_mismatch",
		"profile_tenant_mismatch",
		"provider connection method is unsupported",
		"provider connection state conflict",
		"provider connection was not found",
		"resource upsert if-match is invalid",
		"resource upsert manifest does not match the request",
		"resource upsert request is incomplete",
		"resource upsert requires exactly one condition",
		"resource_id and etag are required",
		"resource_id is required",
		"resource_type must be skill or workflow",
		"runtime-only workflow file is not importable",
		"save cloud refresh token to credential manager",
		"save cloud refresh token to keychain",
		"signed file upload is not configured",
		"signed file upload range is invalid",
		"signed object download failed",
		"signed object exceeds the download limit",
		"signed object hash mismatch",
		"signed object size mismatch",
		"signed object upload failed",
		"signed upload request contains cloud credentials",
		"signed upload request is expired",
		"signed upload request must use https",
		"single put upload omitted its signed request",
		"single put upload omitted signed request",
		"skill has an uncommitted draft; only the committed head can be uploaded",
		"skill has no committed head revision",
		"skill head changed while preparing the cloud upload",
		"skill head contains a file without content",
		"successful cloud upsert omitted the resource",
		"system credential storage is unsupported on this platform",
		"temporary credentials could not be cleared",
		"cloud session could not be cleared from local storage",
		"unwrap credential vault dek",
		"wrap credential vault dek",
	} {
		registerAdditionalErrorAlias(source, "Internal server error", http.StatusInternalServerError, 2000000)
	}

	for _, pattern := range []string{
		"cloud %s package must contain %s",
		"cloud resource zip contains duplicate path %q",
		"lazymind cloud health status %d",
		"lazymind cloud upload ended with status %s",
		"local connection registry returned status %d",
		"source binding authorization returned status %d",
		"unsafe cloud resource path %q",
		"unsafe cloud resource zip path %q",
		"unsupported blob storage backend %q",
		"unsupported cloud resource type %q",
	} {
		registerAdditionalErrorPattern(pattern, "Internal server error", http.StatusInternalServerError, 2000000)
	}
}
