-- +migrate Dialect postgres
ALTER TABLE vocabulary_provider_settings ADD COLUMN local_default_wordbook_id VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE vocabulary_provider_settings ADD COLUMN anki_last_sync_at TIMESTAMPTZ NULL;
ALTER TABLE vocabulary_provider_settings ADD COLUMN anki_last_sync_error TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_words ADD COLUMN origin_type VARCHAR(24) NOT NULL DEFAULT 'user';
ALTER TABLE vocabulary_words ADD COLUMN source_name TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_words ADD COLUMN source_version TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_words ADD COLUMN license_id TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_words ADD COLUMN source_locator TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_words ADD COLUMN archived_at TIMESTAMPTZ NULL;
ALTER TABLE vocabulary_examples ADD COLUMN source_name TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_examples ADD COLUMN source_version TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_examples ADD COLUMN license_id TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_examples ADD COLUMN source_locator TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_source_refs ADD COLUMN document_revision TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_provider_operations ADD COLUMN entity_id VARCHAR(64) NOT NULL DEFAULT '';
CREATE TABLE vocabulary_wordbooks (id VARCHAR(64) PRIMARY KEY, owner_id VARCHAR(64) NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', archived_at TIMESTAMPTZ NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(owner_id,name));
CREATE TABLE vocabulary_wordbook_entries (owner_id VARCHAR(64) NOT NULL, wordbook_id VARCHAR(64) NOT NULL, word_id VARCHAR(64) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(owner_id,wordbook_id,word_id));
CREATE TABLE vocabulary_tags (id VARCHAR(64) PRIMARY KEY, owner_id VARCHAR(64) NOT NULL, name TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(owner_id,name));
CREATE TABLE vocabulary_word_tags (owner_id VARCHAR(64) NOT NULL, word_id VARCHAR(64) NOT NULL, tag_id VARCHAR(64) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(owner_id,word_id,tag_id));
CREATE TABLE vocabulary_example_tags (owner_id VARCHAR(64) NOT NULL, example_id VARCHAR(64) NOT NULL, tag_id VARCHAR(64) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(owner_id,example_id,tag_id));
CREATE TABLE vocabulary_dictionary_imports (id VARCHAR(64) PRIMARY KEY, source_name TEXT NOT NULL, source_version TEXT NOT NULL, license_id TEXT NOT NULL, source_url TEXT NOT NULL, checksum TEXT NOT NULL, imported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(source_name,source_version));
CREATE TABLE vocabulary_dictionary_entries (id VARCHAR(64) PRIMARY KEY, language VARCHAR(16) NOT NULL, normalized_term TEXT NOT NULL, term TEXT NOT NULL, phonetic TEXT NOT NULL DEFAULT '', source_name TEXT NOT NULL, source_version TEXT NOT NULL, license_id TEXT NOT NULL, source_locator TEXT NOT NULL DEFAULT '', priority INTEGER NOT NULL DEFAULT 100, UNIQUE(language,normalized_term,source_name,source_version));
CREATE INDEX idx_vocabulary_dictionary_lookup ON vocabulary_dictionary_entries(language,normalized_term,priority);
CREATE TABLE vocabulary_dictionary_senses (id VARCHAR(64) PRIMARY KEY, entry_id VARCHAR(64) NOT NULL, part_of_speech TEXT NOT NULL DEFAULT '', definition TEXT NOT NULL DEFAULT '', translation TEXT NOT NULL DEFAULT '', sense_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE vocabulary_dictionary_examples (id VARCHAR(64) PRIMARY KEY, entry_id VARCHAR(64) NOT NULL, sense_id VARCHAR(64) NOT NULL DEFAULT '', sentence TEXT NOT NULL, translation TEXT NOT NULL DEFAULT '', source_locator TEXT NOT NULL DEFAULT '', example_order INTEGER NOT NULL DEFAULT 0);
ALTER TABLE vocabulary_review_cards ADD COLUMN example_id VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE vocabulary_review_cards ADD COLUMN card_type VARCHAR(24) NOT NULL DEFAULT 'word_to_meaning';
ALTER TABLE vocabulary_review_cards ADD COLUMN scheduler_version VARCHAR(24) NOT NULL DEFAULT 'go-fsrs/v3.3.1';
ALTER TABLE vocabulary_review_cards ADD COLUMN parameters_version VARCHAR(64) NOT NULL DEFAULT 'default-v3';
ALTER TABLE vocabulary_review_cards DROP CONSTRAINT IF EXISTS vocabulary_review_cards_owner_id_word_id_key;
ALTER TABLE vocabulary_review_cards ADD CONSTRAINT uk_vocabulary_review_card_type UNIQUE(owner_id,word_id,example_id,card_type);
ALTER TABLE vocabulary_review_logs ADD COLUMN idempotency_key VARCHAR(128) NOT NULL DEFAULT '';
CREATE UNIQUE INDEX uk_vocabulary_review_idempotency ON vocabulary_review_logs(owner_id,idempotency_key) WHERE idempotency_key <> '';
CREATE TABLE vocabulary_fsrs_profiles (id VARCHAR(64) PRIMARY KEY, owner_id VARCHAR(64) NOT NULL, name TEXT NOT NULL, weights_json TEXT NOT NULL, desired_retention DOUBLE PRECISION NOT NULL DEFAULT 0.9, maximum_interval_days INTEGER NOT NULL DEFAULT 36500, scheduler_version VARCHAR(24) NOT NULL, source VARCHAR(24) NOT NULL DEFAULT 'default', active BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(owner_id,name));

-- +migrate Dialect sqlite
ALTER TABLE vocabulary_provider_settings ADD COLUMN local_default_wordbook_id TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_provider_settings ADD COLUMN anki_last_sync_at DATETIME NULL;
ALTER TABLE vocabulary_provider_settings ADD COLUMN anki_last_sync_error TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_words ADD COLUMN origin_type TEXT NOT NULL DEFAULT 'user';
ALTER TABLE vocabulary_words ADD COLUMN source_name TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_words ADD COLUMN source_version TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_words ADD COLUMN license_id TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_words ADD COLUMN source_locator TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_words ADD COLUMN archived_at DATETIME NULL;
ALTER TABLE vocabulary_examples ADD COLUMN source_name TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_examples ADD COLUMN source_version TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_examples ADD COLUMN license_id TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_examples ADD COLUMN source_locator TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_source_refs ADD COLUMN document_revision TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_provider_operations ADD COLUMN entity_id TEXT NOT NULL DEFAULT '';
CREATE TABLE vocabulary_wordbooks (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', archived_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(owner_id,name));
CREATE TABLE vocabulary_wordbook_entries (owner_id TEXT NOT NULL, wordbook_id TEXT NOT NULL, word_id TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(owner_id,wordbook_id,word_id));
CREATE TABLE vocabulary_tags (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, name TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(owner_id,name));
CREATE TABLE vocabulary_word_tags (owner_id TEXT NOT NULL, word_id TEXT NOT NULL, tag_id TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(owner_id,word_id,tag_id));
CREATE TABLE vocabulary_example_tags (owner_id TEXT NOT NULL, example_id TEXT NOT NULL, tag_id TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(owner_id,example_id,tag_id));
CREATE TABLE vocabulary_dictionary_imports (id TEXT PRIMARY KEY, source_name TEXT NOT NULL, source_version TEXT NOT NULL, license_id TEXT NOT NULL, source_url TEXT NOT NULL, checksum TEXT NOT NULL, imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(source_name,source_version));
CREATE TABLE vocabulary_dictionary_entries (id TEXT PRIMARY KEY, language TEXT NOT NULL, normalized_term TEXT NOT NULL, term TEXT NOT NULL, phonetic TEXT NOT NULL DEFAULT '', source_name TEXT NOT NULL, source_version TEXT NOT NULL, license_id TEXT NOT NULL, source_locator TEXT NOT NULL DEFAULT '', priority INTEGER NOT NULL DEFAULT 100, UNIQUE(language,normalized_term,source_name,source_version));
CREATE INDEX idx_vocabulary_dictionary_lookup ON vocabulary_dictionary_entries(language,normalized_term,priority);
CREATE TABLE vocabulary_dictionary_senses (id TEXT PRIMARY KEY, entry_id TEXT NOT NULL, part_of_speech TEXT NOT NULL DEFAULT '', definition TEXT NOT NULL DEFAULT '', translation TEXT NOT NULL DEFAULT '', sense_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE vocabulary_dictionary_examples (id TEXT PRIMARY KEY, entry_id TEXT NOT NULL, sense_id TEXT NOT NULL DEFAULT '', sentence TEXT NOT NULL, translation TEXT NOT NULL DEFAULT '', source_locator TEXT NOT NULL DEFAULT '', example_order INTEGER NOT NULL DEFAULT 0);
ALTER TABLE vocabulary_review_cards ADD COLUMN example_id TEXT NOT NULL DEFAULT '';
ALTER TABLE vocabulary_review_cards ADD COLUMN card_type TEXT NOT NULL DEFAULT 'word_to_meaning';
ALTER TABLE vocabulary_review_cards ADD COLUMN scheduler_version TEXT NOT NULL DEFAULT 'go-fsrs/v3.3.1';
ALTER TABLE vocabulary_review_cards ADD COLUMN parameters_version TEXT NOT NULL DEFAULT 'default-v3';
CREATE TABLE vocabulary_review_cards_next (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, word_id TEXT NOT NULL, example_id TEXT NOT NULL DEFAULT '', card_type TEXT NOT NULL DEFAULT 'word_to_meaning', fsrs_card_json TEXT NOT NULL, row_version INTEGER NOT NULL DEFAULT 1, suspended_at DATETIME NULL, scheduler_version TEXT NOT NULL DEFAULT 'go-fsrs/v3.3.1', parameters_version TEXT NOT NULL DEFAULT 'default-v3', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(owner_id,word_id,example_id,card_type));
INSERT INTO vocabulary_review_cards_next (id,owner_id,word_id,example_id,card_type,fsrs_card_json,row_version,suspended_at,scheduler_version,parameters_version,created_at,updated_at) SELECT id,owner_id,word_id,example_id,card_type,fsrs_card_json,row_version,suspended_at,scheduler_version,parameters_version,created_at,updated_at FROM vocabulary_review_cards;
DROP TABLE vocabulary_review_cards;
ALTER TABLE vocabulary_review_cards_next RENAME TO vocabulary_review_cards;
CREATE INDEX idx_vocabulary_review_due ON vocabulary_review_cards(owner_id,suspended_at);
ALTER TABLE vocabulary_review_logs ADD COLUMN idempotency_key TEXT NOT NULL DEFAULT '';
CREATE UNIQUE INDEX uk_vocabulary_review_idempotency ON vocabulary_review_logs(owner_id,idempotency_key) WHERE idempotency_key <> '';
CREATE TABLE vocabulary_fsrs_profiles (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, name TEXT NOT NULL, weights_json TEXT NOT NULL, desired_retention REAL NOT NULL DEFAULT 0.9, maximum_interval_days INTEGER NOT NULL DEFAULT 36500, scheduler_version TEXT NOT NULL, source TEXT NOT NULL DEFAULT 'default', active INTEGER NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(owner_id,name));
