DROP INDEX IF EXISTS idx_vocabulary_wordbook_capability;
DROP TABLE IF EXISTS learning_preanalysis_tasks;
DROP TABLE IF EXISTS learning_review_logs;
DROP TABLE IF EXISTS learning_review_answers;
DROP TABLE IF EXISTS learning_review_session_items;
DROP TABLE IF EXISTS learning_review_sessions;
DROP TABLE IF EXISTS learning_cards;
DROP TABLE IF EXISTS learning_question_instances;
DROP TABLE IF EXISTS learning_dictionary_entries;
DROP TABLE IF EXISTS learning_dictionary_imports;
DROP TABLE IF EXISTS learning_presets;
DROP TABLE IF EXISTS learning_book_entries;
DROP TABLE IF EXISTS learning_books;
DROP TABLE IF EXISTS learning_contents;
DROP TABLE IF EXISTS learning_occurrences;
DROP TABLE IF EXISTS learning_subjects;
DROP TABLE IF EXISTS learning_knowledge_base_capabilities;
DROP TABLE IF EXISTS learning_capability_profiles;
ALTER TABLE vocabulary_wordbooks DROP COLUMN question_types_json;
ALTER TABLE vocabulary_wordbooks DROP COLUMN capability_key;
